### ISSUE TITLE
RSpec/FilePath ignores plural acronym definitions

### ISSUE THREAD

**Issue by jibiel** [rubocop-hq/rubocop-rspec#1012]
```ruby
# config/initializers/inflections.rb

ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'URLs'
end
```
```ruby
# spec/operations/urls/generate_spec.rb

RSpec.describe URLs::Generate do
  # ...
end
```
Rails behaves as expected with these inflections. Plural acronyms are even used in the [documentation examples](https://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html#method-i-acronym). But RuboCop throws an offense:

```
Offenses:

spec/operations/urls/generate_spec.rb:3:1: C: RSpec/FilePath: Spec path should end with ur_ls/generate*_spec.rb. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FilePath)
RSpec.describe URLs::Generate do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

No offenses if one replaces `URLs` with `URL` and `/urls/` with `/url/` in the above example though.

**Comment by pirj** [comment]
RuboCop is a static analysis tool, and it doesn't load up Rails env or and of the Rails files nor it's in any way rely on Rails with a small exception in `FilePath` - it ignores specs with Rails metadata (e.g. `type: :request`).

You may take a look at [`CustomTransform` config option](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FilePath):

> With the configuration option `CustomTransform` modules or classes can be specified that should not as usual be transformed from CamelCase to snake_case (e.g. 'RuboCop' => 'rubocop' ).

There is [an example of how it works in specs](https://github.com/rubocop-hq/rubocop-rspec/blob/master/spec/rubocop/cop/rspec/file_path_spec.rb#L215).

Would be very nice of you if you sent a pull request updating the documentation for this cop on how to use this option.
