### ISSUE TITLE
Remove `UselessMethodDefinition` disable statement

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rubocop-rspec#1030]
https://github.com/rubocop-hq/rubocop/pull/8659 the bug that led to a false positive has been fixed.
It's safe to remove it after the next minor RuboCop release.

**Comment by tejasbubane** [comment]
I see only two disables for this cop: https://github.com/rubocop-hq/rubocop-rspec/blob/f1f369dd022111e84a5564169f13a597a7b47bf4/spec/support/expect_offense.rb

I wonder why they are not reported by `Lint/RedundantCopDisableDirective`.

**Comment by pirj** [comment]
I guess we can safely remove those two disable statements.

Nice catch that `RedundantCopDisableDirective` misses that! Would you file a ticket for https://github.com/rubocop-hq/rubocop? I usually check `edge-rubocop` build, and only start fixing on our side if it's red (and merge when it's released in `rubocop`), but the build wasn't red after merge of the https://github.com/rubocop-hq/rubocop/pull/8659 😕

**Comment by pirj** [comment]
This has been removed.
I'm not sure if filing this case is worth it.
