### ISSUE TITLE
Cop idea: Check for Global DSL

### ISSUE THREAD

**Issue by MatheusRich** [rubocop-hq/rubocop-rspec#1031]
RSpec allows disabling the global DSL by using `config.expose_dsl_globally = false`.

This is nice, but in a large project it can be hard to change, so rubocop-rspec can help on this migration.

```ruby
# Bad
describe MyClass do
  # ...
end

# Good
RSpec.describe MyClass do
  # ...
end
```

I can provide a PR if this idea is approved.

**Comment by pirj** [comment]
Sorry, it's a non-goal for RuboCop RSpec https://docs.rubocop.org/rubocop-rspec/index.html#enforcing-an-explicit-rspec-receiver-for-top-level-methods-disabling-monkey-patching

I believe RSpec should provide necessary tooling to assist with the migration to RSpec 4, like it was with [RSpec 3 and transspec](http://rspec.info/upgrading-from-rspec-2/).

**Comment by MatheusRich** [comment]
I didn't know about Transpec. Thanks!
