### ISSUE TITLE
RSpec/EmptyExampleGroup reports on skipped examples/axample groups

### ISSUE THREAD

**Issue by obfuscoder** [rubocop-hq/rubocop-rspec#1032]
When specifying tests, but not yet implementing them, I usually do this:

```
  describe '#some_method' do
    it 'behaves like this and that'
  end
```

or

```
  describe '#some_method' do
    skip 'we still need to write the specs here'
  end
```

When running specs, those pending specs show up as TODOs.

Upgrading from rubocop-rspec 1.42.0 to 1.43.2 now reports those lines with:

```
C: RSpec/EmptyExampleGroup: Empty example group detected.
    describe '#some_method' do
    ^^^^^^^^^^^^^^^^^^^^^^^
```

We do not want to disable this cop as sometimes developers tend to forget to add anything in an example group, but we don't want it to report on groups including pending specs which already show up on the rspec output.

**Comment by pirj** [comment]
Thanks for reporting. This [has been fixed](https://github.com/rubocop-hq/rubocop-rspec/pull/1020/files#diff-9a93f375888ae8523835d1127abf853cR253), just not released yet.
Appreciate if you use `master` and confirm that it works for you.
