### ISSUE TITLE
Version conflict for rubocop-rspec 1.44.0 with rubocop-ast 0.8

### ISSUE THREAD

**Issue by RST-J** [rubocop-hq/rubocop-rspec#1046]
I just updated all the rubocop gems we use in our project and found that `rubocop` cannot load `rubocop-rspec` afterwards.
`Unable to activate rubocop-rspec-1.44.0, because rubocop-ast-0.8.0 conflicts with rubocop-ast (~> 0.7.1)`

I am pretty sure this is due to the newly added `rubocop-ast` runtime dependency in the [gemspec](https://github.com/rubocop-hq/rubocop-rspec/blob/v1.44.0/rubocop-rspec.gemspec#L40)
```ruby
spec.add_runtime_dependency 'rubocop-ast', '~> 0.7.1'
```
Is there a particular reason to limit the minor version?

**Comment by PhilCoggins** [comment]
Here's a PR, I have no idea if this locking is for any particular reason but at least get a build running on it.

**Comment by pirj** [comment]
My bad guys, I don't know what I was thinking.
Thanks for the PR, @PhilCoggins !

**Comment by bquorning** [comment]
Fixed in v1.44.1. Thanks for reporting.
