### ISSUE TITLE
`RSpec/ScatteredSetup` does not allow custom example group blocks

### ISSUE THREAD

**Issue by dvandersluis** [rubocop-hq/rubocop-rspec#1067]
In our codebase we have a custom method that creates an example group with various metadata depending on arguments. Any callbacks done within that custom example group are flagged by `RSpec/ScatteredSetup`.

The same thing happens with [`alias_example_group_to`](https://relishapp.com/rspec/rspec-core/docs/example-groups/aliasing).

It'd be great if custom example groups can be added to the cop configuration similarly to `RSpec/EmptyExampleGroup`. BTW -- interestingly, `RSpec/ScatteredLet` does not register with the same setup.

```ruby
# spec_helper.rb
config.alias_example_group_to :foobar, foo: true

# foobar_spec.rb
RSpec.describe Foo do
  before { do_something }

  foobar do
    before { do_something_else }
  end
end
```

```
$ rubocop spec/foobar_spec.rb
Inspecting 1 file
C

Offenses:

spec/foobar_spec.rb:2:3: C: RSpec/ScatteredSetup: Do not define multiple before hooks in the same example group (also defined on line 5).
  before { do_something }
  ^^^^^^^^^^^^^^^^^^^^^^^
spec/foobar_spec.rb:5:5: C: RSpec/ScatteredSetup: Do not define multiple before hooks in the same example group (also defined on line 2).
    before { do_something_else }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
```

**Comment by pirj** [comment]
Thanks for reporting.
In version 2.0 we're including #956 that will allow configuring your custom RSpec DSL, specifically example group aliases.
Also, we're dropping the old way of customizing `RSpec/EmptyExampleGroup` in https://github.com/rubocop-hq/rubocop-rspec/pull/1007.
We're working hard to get 2.0 ASAP, keep tight and watch for the releases.

**Comment by dvandersluis** [comment]
Great, thanks @pirj!
