### ISSUE TITLE
Bug with `RSpec/FactoryBot/CreateList` and I'm a bit unsure as to why.

### ISSUE THREAD

**Issue by snood1205** [rubocop-hq/rubocop-rspec#1068]
## Expected behavior

Rubocop should lint the file appropriately 
## Actual behavior

Describe here what actually happened.
The stack trace was too long to paste in the issue so here is a gist with it. https://gist.github.com/snood1205/e5260408de9c178f6719460a59dbd777

Basically, the issue was with `RSpec/FactoryBot/CreateList` running incorrectly.

## Steps to reproduce the problem

The file that I have that is creating said problem is this
```ruby
# frozen_string_literal: true

require 'rails_helper'

RSpec.describe 'POST /login', type: :request do
  let(:user) { Fabricate(:user) }
  let(:url) { '/login' }
  let(:params) do
    Hash[
   user: {
     email: user.email,
     password: user.password
   }
    ]
  end

  context 'when params are correct' do
    before do
      post url, params: params
    end

    it 'returns 200' do
      expect(response).to have_http_status(200)
    end

    it 'returns a JWT Authentication Token' do
      expect(response).to have_header 'Authorization'
    end

    it 'gives a valid JWT token' do
      token = decoded_jwt_token_from_response(response)
      expect(token.first).to have_key 'sub'
    end
  end
end
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ bundle exec rubocop -V
1.1.0 (using Parser 2.7.2.0, rubocop-ast 1.1.0, running on ruby 2.7.2 x86_64-darwin19)
  - rubocop-performance 1.8.1
  - rubocop-rails 2.8.1
  - rubocop-rspec 1.42.0
```

**Comment by pirj** [comment]
Thanks for reporting.

@denkoleda is right. Sorry for the trouble, there's a workaround to explicitly specify `2.0.0.pre` in your `Gemfile`.

Speaking of the code, I don't see `create_list` there.
