### ISSUE TITLE
false positive in RSpec/FilePath

### ISSUE THREAD

**Issue by silva96** [rubocop-hq/rubocop-rspec#1111]
upgrading to 2.1.0 broke this pattern I've been using for a while to keep spec files smaller

I have all this files:

![image](https://user-images.githubusercontent.com/4019924/102702001-36cfef80-423c-11eb-8454-63f0067a2a23.png)

For example, I test all scopes together in same file
```ruby
# spec/models/post/scopes_spec.rb
RSpec.describe Post, type: :model do
  describe 'Scopes' do
...
```

now gives 

```
spec/models/post/scopes_spec.rb:5:1: C: RSpec/FilePath: Spec path should end with post*_spec.rb.
RSpec.describe Post, type: :model do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

But clearly, you can see spec/models/post/scopes_spec.rb matches post*_spec.rb.

Changing to `'Post'` instead of `Post`

```ruby
RSpec.describe 'Post', type: :model do
```

Shows no Error, but it's not ideal because i can't use "described_class"

For now, I renamed the files to for example:

spec/models/post/post_scopes_spec.rb

which is redundant.

**Comment by pirj** [comment]
I agree with the cop.
Shouldn't `spec/models/post/scopes_spec.rb` contain:
```ruby
RSpec.describe Post, 'scopes', type: :model do
```
what do you think?

**Comment by silva96** [comment]
Gives another error.

![image](https://user-images.githubusercontent.com/4019924/103027518-c9220d00-4534-11eb-84f3-d0fbee33e68c.png)

**Comment by pirj** [comment]
I suggest you turn off `RSpec/DescribeMethod` cop, as it doesn't alight with your spec directory layout.
It's not uncommon that some cops can be partially incompatible, even if both enabled by default. At least in some cases, like this one of yours.

**Comment by silva96** [comment]
I rather keep files double named 'post/post_scopes_spec.rb'. 

Just want to point out this appeared after the upgrade, so this sounds like a regression to me

**Comment by pirj** [comment]
Not a regression, but rather an improvement, the `RSpec/FilePath` cop doesn't miss offences that it used to miss.
