### ISSUE TITLE
False positive of `RSpec/FilePath`

### ISSUE THREAD

**Issue by AlexWayfer** [rubocop-hq/rubocop-rspec#1131]
Project: https://github.com/AlexWayfer/formalism-model_forms

Offense:

```
> bundle exec rubocop
Inspecting 18 files
...............C..

Offenses:

spec/formalism/model_forms/update_spec.rb:3:1: C: RSpec/FilePath: Spec path should end with formalism/model_forms*_spec.rb.
describe Formalism::ModelForms do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

18 files inspected, 1 offense detected

> find spec/ -path "spec/formalism/model_forms*_spec.rb"
spec/formalism/model_forms/version_spec.rb
spec/formalism/model_forms/update_spec.rb

> bundle exec rubocop -V
1.9.1 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 3.0.0 x86_64-linux)
  - rubocop-performance 1.9.2
  - rubocop-rspec 2.2.0
```

**Comment by pirj** [comment]
You have [`Formalism::ModelForms::Update`](https://github.com/AlexWayfer/formalism-model_forms/blob/125b6adb8cfcedf6442cae5b4c752e4866b06034/lib/formalism/model_forms/update.rb#L6), and [this `MyProject::Forms::User::Update `](https://github.com/AlexWayfer/formalism-model_forms/blob/125b6adb8cfcedf6442cae5b4c752e4866b06034/spec/formalism/model_forms/update_spec.rb#L7):
```ruby
    describe Formalism::ModelForms do
	# rubocop:enable RSpec/FilePath
	describe MyProject::Forms::User::Update do
```
[inherits](https://github.com/AlexWayfer/formalism-model_forms/blob/93de44d444d21e649dc42f04fddedc0b58dfdb8c/spec/spec_helper.rb#L44) from `Forms::Model::Update` (is it a dynamically generated class?).

To me, it sounds fair to write the top-level's group class as:
```ruby
RSpec.describe 'Formalism::ModelForms::Update' do
```

Does it sound reasonable and appeases the cop at the same time, @AlexWayfer ?

**Comment by AlexWayfer** [comment]
> [inherits](https://github.com/AlexWayfer/formalism-model_forms/blob/93de44d444d21e649dc42f04fddedc0b58dfdb8c/spec/spec_helper.rb#L44) from `Forms::Model::Update` (is it a dynamically generated class?).

Yes.



> To me, it sounds fair to write the top-level's group class as:
> 
> ```ruby
> RSpec.describe 'Formalism::ModelForms::Update' do
> ```
> 
> Does it sound reasonable and appeases the cop at the same time, @AlexWayfer ?

I can do this, but do you understand that this cop offense with pattern, by which the file can be find? So it's still an issue of the cop.

**Comment by pirj** [comment]
Not really. The cop is sophisticated enough to understand that it's ok for a file called e.g. `spec/formalism/model_forms/update_spec.rb` to be a home for such a top-level group:
```ruby
RSpec.describe Formalism::ModelForms, '#update' do
```

Agree, the offence message is not very clear in your case.

A pull request to improve the message is welcome as always. Thanks for reporting!
