### ISSUE TITLE
Add additional namespace to cops

### ISSUE THREAD

**Issue by backus** [rubocop-hq/rubocop-rspec#232]
After @JonRowe's feedback in #228 I'd like to start by at least adding an additional namespace for our cops. This change can be pretty simple:

``` ruby
diff --git i/lib/rubocop/cop/rspec/leading_subject.rb w/lib/rubocop/cop/rspec/leading_subject.rb
index c9b813a..d87e927 100644
--- i/lib/rubocop/cop/rspec/leading_subject.rb
+++ w/lib/rubocop/cop/rspec/leading_subject.rb
@@ -31,6 +31,10 @@ module RuboCop

         MSG = 'Declare `subject` above any other `let` declarations'.freeze

+        def self.cop_name
+          "RSpec/Style/LeadingSubject"
+        end
+
         def_node_matcher :subject?, '(block $(send nil :subject ...) args ...)'

         def on_block(node)
```

we could also add another namespace (might be too much nesting idk) and define a `cop_name` method which just defines `name.split('::').last(3).join('/')`. This might be a mess though since, as I've noted before, we can't just do `class RuboCop::RSpec::Cop < RuboCop::Cop::Cop` because `RuboCop::Cop::Cop` mutates some class level state on the `inherited` hook which I don't know how to avoid.

The point of this name spacing would be to start creating an end-user visible differentiation between stylistic and opinionated cops which should be treated differently from linting and best practice cops

**Comment by backus** [comment]
@bquorning interested what you think here. I know there are a few parts of the rubocop codebase which assume a cop name has a single namespace but, as far as I can tell, deviating from this contract doesn't break anything

**Comment by bquorning** [comment]
I’m not completely sold on the idea. This feels like something that belongs inside RuboCop proper.

They have the Rails cops (which really should be a separate project) – they ought to be namespaced as well, I guess.

**Comment by pirj** [comment]
FactoryBot and Rails namespaces were added in #1019
Speaking of separating cops by their importance or purpose seems to be a task nobody is willing to take.
