### ISSUE TITLE
"Common edge cases" shared examples

### ISSUE THREAD

**Issue by backus** [rubocop-hq/rubocop-rspec#388]
We should add some shared examples to our specs which include tests like 

```ruby
it 'does not encounter an error when handling an empty describe' do
  expect { inspect_source(cop, 'RSpec.describe(User) do end', 'a_spec.rb') }
    .not_to raise_error
end
```

and then in our spec helper we can include these shared examples for all specs in the `spec/rubocop/cop/rspec` directory.

This should help us avoid easy to overlook regressions like #385

**Comment by dgollahon** [comment]
I think that #623 and #624 reinforce the need for this. We could hand-craft some common weird cases and then use them as a shared example for every cop as a strong starting point, but I also think it would be worthwhile to find a few popular repos that use `rspec`, get a git reference for a specific commit (so the build doesn't fluctuate suddenly) and just run `rubocop-rspec` over 5-10 projects and check only for crashes.

Further advantage for the corpus testing approach is that we could add a tool could be something like `bin/test-drive` that would show the offenses a specific / your new cop finds on the available projects so you can do a quick sanity check of your proposed cop / cop modifications. If we wanted to get really complex, we could build a tool like this which is source-aware and could show you the _diff_ of offenses generated for each modification you make to the codebase, which I think would be fantastic.

**Comment by bquorning** [comment]
What a great idea. I guess such a tool would be as useful for vanilla RuboCop as for RuboCop-RSpec.

**Comment by dgollahon** [comment]
> I guess such a tool would be as useful for vanilla RuboCop

Yeah, absolutely. We could test-drive it here and maybe introduce it into rubocop proper once we iron out the kinks.

**Comment by dgollahon** [comment]
I *might* have some time in the next couple of days to take a stab at it.
