### ISSUE TITLE
Potentially misleading guidance for InstanceVariable cop

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop-rspec#414]
"Use `let` instead of an instance variable" doesn't make sense in cases where an instance variable is used unnecessarily rather than a local variable. For example within a `before` block, assuming `@foo` isn't used anywhere else:

```ruby
before do
  @foo = 'bar'
  widget.stub(@foo)
end
```

**Comment by pirj** [comment]
It might still be used somewhere in the shared example, and we won't be able to detect that usage.
Did you have a more generic message in mind, like "Don't use an instance variable"?

**Comment by andyw8** [comment]
How about: "Avoid instance variables – use `let`, a method call, or a local variable (if possible)"

**Comment by pirj** [comment]
This sounds just right.
@bquorning @Darhazer WDYT? I can make this change quickly.

**Comment by bquorning** [comment]
I like it.
