### ISSUE TITLE
Proposal: Detect use of `context` for method names instead of `describe`

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop-rspec#417]
I often see things like:

`context "#foo_bar"`

rather than

`describe "#foo_bar"`

The linter could check character of the string for a `.` or `#`.

**Comment by pirj** [comment]
Addressed in #492.
Or should a companion cop be created?

**Comment by andyw8** [comment]
Oh interesting. This would catch the issue, but it would be nice if it recognised `.` and `#` as special cases and recommended using `describe`.
