### ISSUE TITLE
Cop idea: Replace FactoryGirl association shorthand with call to `#association`

### ISSUE THREAD

**Issue by Drenmi** [rubocop-hq/rubocop-rspec#432]
I have started preferring `association :foo, ...` over the shorthand `foo` in factories.

It would be nice to have a cop for this. 🙂

**Comment by backus** [comment]
👍

**Comment by pirj** [comment]
Both are valid syntaxes.

The only downside of the ["implicit" style](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#specifying-the-factory) I could find and recall is:

> Please note that the strategy: :build option must be passed to an explicit call to association, and cannot be used with implicit associations:

```ruby
factory :post do
  # ...
  author strategy: :build    # <<< this does *not* work; causes author_id to be nil
```

Also, it seems that the detection of implicit associations will suffer from false positives. This makes this syntax ambiguous.

[Implicit attributes](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#as-implicit-attributes) have the same syntax as well:

```ruby
FactoryBot.define do
  sequence :email do |n|
    "person#{n}@example.com"
  end
end

factory :user do
  email # Same as `email { generate(:email) }`
end
```

[Traits can be defined the same way](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#as-implicit-attributes-1):

```ruby
factory :story do
  trait :published do
    published { true }
  end

  trait :week_long_publishing do
    start_at { 1.week.ago }
    end_at { Time.now }
  end

  factory :week_long_published_story_with_title do
    published
    week_long_publishing
    title { "Publishing that was started at #{start_at}" }
  end
end
```

All in all, implicit association syntax is mostly harmless, while:
```ruby
authod { create(:author) }
```
is way worse, as it undermines other strategies.
