### ISSUE TITLE
RSpec/DescribedClass does not handle nested describes

### ISSUE THREAD

**Issue by dgollahon** [rubocop-hq/rubocop-rspec#604]
Example:
```ruby
RSpec.describe Foo do
  it 'has a baz' do
    expect(described_class.baz).to eql('baz')
  end

  describe Bar do
    it 'has a matching baz implementation' do
      expect(Foo.baz).to eql(Bar.baz)
    end
  end
end
```

Outcome:
![image](https://user-images.githubusercontent.com/4211073/39402861-c72c346e-4b20-11e8-8226-f74535509832.png)

The cop wrongly flags `Foo` and suggests a semantically invalid change. Meanwhile `Bar` is not highlighted. `RSpec/DescribedClass` should account for nested class describes.

**Comment by bquorning** [comment]
It looks like we have a spec for the *opposite* case here: https://github.com/rubocop-hq/rubocop-rspec/blob/9c27c4e7eba527a02657f53246e32596bb6ce8e0/spec/rubocop/cop/rspec/described_class_spec.rb#L131-L142

**Comment by dgollahon** [comment]
...wow, that's really strange.

**Comment by bquorning** [comment]
I just tried that code out, and our spec is wrong. It was among the first specs added to that file, so perhaps that’s how RSpec worked 3 years ago?

**Comment by dgollahon** [comment]
> so perhaps that’s how RSpec worked 3 years ago?

I doubt it, but maybe..? Seems more likely to be an oversight or misunderstanding, but perhaps.

**Comment by bquorning** [comment]
It looks like the `scope_change?` method in `DescribedClass` doesn’t detect when the scope changes on the inner `describe` call. I’m not sure how to fix it though…

**Comment by tom-lord** [comment]
Just ran into this, too.

As with [the pending `FactoryBot/CreateList`](https://github.com/rubocop-hq/rubocop-rspec/commit/59dec67cc45e8a921c9b639b8c9ee3d9fd6c550f), this bug is particularly surprising in conjunction with `rubocop --safe-auto-correct`.
