### ISSUE TITLE
Cop idea: detect usage of `.never` and suggest `not_to receive` instead

### ISSUE THREAD

**Issue by Darhazer** [rubocop-hq/rubocop-rspec#607]
Bad:
`expect(instance).to receive(:method).never`

Good:
`expect(instance).not_to receive(:method)`

**Comment by bquorning** [comment]
Sounds like a good cop. The recommendation applies even if using `with`, right?

**Comment by Darhazer** [comment]
> The recommendation applies even if using with, right?

Correct.
` expect(A).not_to receive(:foo).with(2)`
is exactly the same as
`expect(A).to receive(:foo).with(2).never`
