### ISSUE TITLE
Invitation to join RuboCop HQ

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop-rspec#620]
Hey there!

I've recently created https://github.com/rubocop-hq to serve as the new home of RuboCop and related projects. I'd love to see `rubocop-rspec` live under the same organization as RuboCop itself. 

Let me know if you're interested in doing this and we'll hash out the details later.

**Comment by backus** [comment]
I'm all for it but I haven't been contributing to the project for the last ~9 months so I'll give final say to @bquorning, @Darhazer, @dgollahon

**Comment by bquorning** [comment]
I guess it would make a lot of sense to users of different RuboCop projects to have them collected under the same GitHub organization.

But how would it work in practice? Would they continue to run as independent projects? Would there be e.g. more “coordinated” releases to avoid e.g. a new release of RuboCop not working with the latest release of RuboCop-RSpec?

Who will be “owners” of the rubocop-hq organization? I guess these people will be allowed to give or remove write / admin rights to each repository in the organization.

> Let me know if you're interested in doing this and we'll hash out the details later.

Yes, I’m interested 😃

**Comment by bbatsov** [comment]
> But how would it work in practice? Would they continue to run as independent projects? Would there be e.g. more “coordinated” releases to avoid e.g. a new release of RuboCop not working with the latest release of RuboCop-RSpec?

Yeah, they will, although I hope that eventually we'll get to a point of stronger collaboration:

* stable (and official) extension API (which should solve the breakages problem)
* common conventions about configuration and documentation employed by all RuboCop projects
* common website (I just bought RuboCop.org) where to put all the documentation for all RuboCop projects

For a very long time things have been happening in a disconnected fashion and I was to finally change this. :-)

> Who will be “owners” of the rubocop-hq organization? I guess these people will be allowed to give or remove write / admin rights to each repository in the organization.

The owners now are me, @jonas054 and @yujinakayama (the "original RuboCop team"), but I'm fine with making more people owners there if necessary. You and all RuboCop RSpec devs will be owners of the projects in the new org and I'd fine with making some of you committers in RuboCop so you can address some issues there directly if needed. 

I'll send invitations to all of you, so you can do the transfer. 

P.S. Take a look at https://speakerdeck.com/bbatsov/all-about-rubocop-rubykaigi-2018

**Comment by bquorning** [comment]
@Darhazer @dgollahon Do you have any reservations or other comments? Otherwise I’ll transfer our repository in a few days.

**Comment by Darhazer** [comment]
I'm all in

**Comment by dgollahon** [comment]
@bquorning @bbatsov No real reservations.

I do think I think most cop decisions will probably work best when running as largely independent projects, at least for the foreseeable future.

That said, I am excited about a lot of the ways we can collaborate more. In particular, I'm very eager for

> stable (and official) extension API (which should solve the breakages problem)

and am definitely willing to help out with that.

As an aside, @Darhazer , @bquorning if the eventual extension setup becomes simple, we should be able to split out our FactoryBot and any other non-rspec cops, which I think would be smart.

@bquorning Transfer at will.

**Comment by bbatsov** [comment]
> As an aside, @Darhazer , @bquorning if the eventual extension setup becomes simple, we should be able to split out our FactoryBot and any other non-rspec cops, which I think would be smart.

Indeed. 

I see that @bquorning has already executed the transfer. Thanks for the support of the idea, guys!
