### ISSUE TITLE
RSpec/OverwritingSetup crashes on non-symbol setup names

### ISSUE THREAD

**Issue by dgollahon** [rubocop-hq/rubocop-rspec#624]
I have some code that does something roughly along the lines of

```ruby
RSpec.describe Foo do
  let(:params) do
    {
      a: a,
      b: b
    }
  end

  let(:a) { 1 }
  let(:b) { 2 }

  %i[a b].each do |parameter|
    context "when #{parameter} is missing"  do
      let(name) { nil }

      it 'is not valid' do
        expect(Foo.new(params)).not_to be_valid
      end
    end
  end
end
```

I probably would't write the spec in that way today, but I'm sure I'm not the only person who's written setup using a dynamic name at some point in time.

Unfortunately, RSpec/OverwritingSetup now crashes in this case because it assumes a string/symbol will be present. We should update the node pattern or add a guard to make sure the argument to `let`, `subject`, etc. is actually a string or symbol we can compare.

Minimized reproduction:

```ruby
RSpec.describe 'test' do
  let(:foo) { 'foo' }
  name = :bar
  let(name) { 'bar' }
end
```

Trace:

> An error occurred while RSpec/OverwritingSetup cop was inspecting /Users/gollahon/dev/foo_spec.rb:1:0.
undefined method `value' for s(:lvar, :name):RuboCop::AST::Node
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:51:in `block in find_duplicates'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:185:in `block in each_child_node'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:183:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:183:in `each_child_node'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:47:in `find_duplicates'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:34:in `on_block'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:105:in `with_cop_error_handling'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:45:in `investigate'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:114:in `investigate'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:102:in `offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:265:in `inspect_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:212:in `block in do_inspection_loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:244:in `block in iterate_until_no_changes'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `iterate_until_no_changes'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:208:in `do_inspection_loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:129:in `file_offense_cache'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:39:in `run'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:160:in `execute_runner'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:88:in `execute_runners'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:41:in `run'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/exe/rubocop:13:in `block in <top (required)>'
/Users/gollahon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/exe/rubocop:12:in `<top (required)>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/rubocop:23:in `load'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/rubocop:23:in `<main>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dgollahon** [comment]
I wanted to check if an unrelated property held: "Do we detect overwritten setup if one is defined with a symbol and the other is defined with a string?" Even though this is unlikely to occur, it'd be valid and easy to check these so I tried:

```ruby
RSpec.describe 'test' do
  let(:foo)  { 'foo' }
  let('foo') { 'bar' }
end
```

Only to learn that we crash on this case as well.

> An error occurred while RSpec/OverwritingSetup cop was inspecting /Users/gollahon/dev/foo_spec.rb:1:0.
undefined method `value' for s(:str, "foo"):RuboCop::AST::StrNode
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:51:in `block in find_duplicates'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:185:in `block in each_child_node'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:183:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:183:in `each_child_node'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:47:in `find_duplicates'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:34:in `on_block'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:105:in `with_cop_error_handling'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:45:in `investigate'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:114:in `investigate'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:102:in `offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:265:in `inspect_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:212:in `block in do_inspection_loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:244:in `block in iterate_until_no_changes'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `iterate_until_no_changes'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:208:in `do_inspection_loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:129:in `file_offense_cache'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:39:in `run'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:160:in `execute_runner'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:88:in `execute_runners'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:41:in `run'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/exe/rubocop:13:in `block in <top (required)>'
/Users/gollahon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/exe/rubocop:12:in `<top (required)>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/rubocop:23:in `load'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/rubocop:23:in `<main>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Darhazer** [comment]
`undefined method value' for s(:str, "foo"):RuboCop::AST::StrNode `

The interesting part is that str is a basic literal, but str_node doesn't include BasicLiteralNode.
