### ISSUE TITLE
Removal of Rails cops

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop-rspec#630]
Hi @bbatsov 

I saw from your RubyKaigi talk that one of the goals for RuboCop 1.0 includes removing the Rails cops.

https://speakerdeck.com/bbatsov/all-about-rubocop-rubykaigi-2018?slide=160

Is there an intention to move these into a plugin, similar to rubocop-rspec?

I notice that the gem name "rubocop-rails" is unfortunately already taken, but for a different purpose (linting the Rails framework):

https://rubygems.org/gems/rubocop-rails/versions/1.4.0

**Comment by koic** [comment]
Hi @andyw8. Thank you for opening question.

I'm asking @toshimaru (He is gem name owner) whether he can transfer the gem name of rubocop-rails to the RuboCop team.
rubocop-hq/rubocop#5976 is the related issue.

Apart from the issue of gem name, development to extract RuboCop Rails from RuboCop Core will start from now.

**Comment by bquorning** [comment]
The only Rails-specific cop in rubocop-rspec is `RuboCop::Cop::RSpec::Rails::HttpStatus`, but I don’t know if it makes sense to extract that into the rubocop-rails project. Or if we should have a rubocop-rspec-rails project for only one cop…

**Comment by bbatsov** [comment]
Yeah, probably this one can stay here.

**Comment by andyw8** [comment]
Thanks for the information.
