### ISSUE TITLE
RSpec/EmptyLineAfterExampleGroup invalid behavior

### ISSUE THREAD

**Issue by mensfeld** [rubocop-hq/rubocop-rspec#648]
When I have a conditional spec based on some external arguments EmptyLine linter requires a new line after the spec but this does not seem right. I use flags like this sometimes for extensive integration testing of some internal components that I want to run only on special occasions. For such cases, this linter shouldn't require a new line as it doesn't make sense.

```ruby
describe Example do
  if ENV['FLAG']
    describe 'something funny' do
      let (:name) { 45 }

      it 'whatever' do
      end
    end
  end
end
```

Please use this code for reproduction:

```
git clone https://github.com/mensfeld/broken-rubocop-rspec4.git
cd broke-rubocop-rspec4
./run.sh
```

Result:

```
Inspecting 2 files
.C

Offenses:

spec/example_spec.rb:8:5: C: RSpec/EmptyLineAfterExampleGroup: Add an empty line after describe.
    end
    ^^^
```

**Comment by bquorning** [comment]
@Darhazer This bug seems to be in the `node.parent.children.last` code that I copied from `EmptyLineAfterSubject` to `EmptyLineAfterExampleGroup`. I reduced the reproduction code to this:

```rb
if ENV['FLAG']
  describe Foo do
  end
end
```

Here, the offensive node’s `parent` is the `IfNode`:

```
s(:if,
  s(:send,
    s(:const, nil, :ENV), :[],
    s(:str, "FLAG")),
  s(:block,
    s(:send, nil, :describe,
      s(:const, nil, :Foo)),
    s(:args), nil), nil)
```

and `node.parent.children.last` is `nil`, so `node.equal?(node.parent.children.last)` evaluates to `false`.

What do you think? Should we just add a `return if node.parent && !node.parent.block_type?` guard?

**Comment by mensfeld** [comment]
I should get a badge like "bug hunter" or something :D

**Comment by bquorning** [comment]
Definitely!

**Comment by bquorning** [comment]
I think I’ll start mentioning you on the release PRs. Would you be ok with testing a github SHA, or would you need a rubygems pre-release gem?

**Comment by mensfeld** [comment]
Pre releases would be more convinient but I think I can adapt and use shas :) - feel free to ping me anytime!

**Comment by mensfeld** [comment]
@Darhazer @bquorning any chance for a pre release? This issue is breaking my CI integration :D

**Comment by Darhazer** [comment]
@dgollahon can you cut a new release? I don't have permission to put to Rubygems yet
