### ISSUE TITLE
False positive from FactoryBot/DynamicAttributeDefinedStatically using a block outside DSL

### ISSUE THREAD

**Issue by tjwp** [rubocop-hq/rubocop-rspec#655]
`FactoryBot/DynamicAttributeDefinedStatically` reports a false positive when a block is used in a factory outside of the `FactoryBot` DSL.

Here is a simplified example

```ruby
FactoryBot.define do
  factory :post do

    %i(user anonymous).each do |comment_type|
      trait :commented do
        association :comment, factory: [:comment, comment_type]
      end
    end
  end
end
```

Instead of `association` being recognized as part of the DSL an offense is flagged:

```
spec/factories/test.rb:8:9: C: FactoryBot/DynamicAttributeDefinedStatically: Use a block to set a dynamic value to an attribute.
        association :comment, factory: [:comment, comment_type]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If auto-correct is used, then it modifies the "offending" line resulting in invalid code:

```ruby
association { :comment }, factory: [:comment, comment_type]
```

Versions:
rubocop-rspec 1.27.0
rubocop 0.57.2 (using Parser 2.5.1.0, running on ruby 2.4.1 x86_64-darwin16)

**Comment by Darhazer** [comment]
The question here is should we allow usage of `lvar` as a static, or should we just add an exception for DSL methods like association? WDYT?

cc: @jonatas @abrom
