### ISSUE TITLE
allow + to receive vs stub

### ISSUE THREAD

**Issue by Ana06** [rubocop-hq/rubocop-rspec#663]
A cop to enforce one of them would be nice. I think `allow` + `to_receive` is preferred.

**Comment by Darhazer** [comment]
To use `stub` you have to allow the old syntax (configure mock syntax with `should`)
This false in the non-goals section for rubocop-rspec as RSpec can enforce using allow + receive on itsown

**Comment by Ana06** [comment]
@Darhazer 

> RSpec can enforce using allow + receive on its own

what do you exactly mean with this? :confused:

**Comment by Darhazer** [comment]
To use `stub` you have to enable the `should` syntax for rspec-mocks. 
See the non-goals section in rubocop-rspec's readme

**Comment by Ana06** [comment]
@Darhazer 

> To use stub you have to enable the should syntax for rspec-mocks.
See the non-goals section in rubocop-rspec's readme

ok, thanks!

**Comment by dgollahon** [comment]
Maybe we should add a small note to the README noting that banning `should` also applies to `stub`.
