### ISSUE TITLE
Implicit subject?

### ISSUE THREAD

**Issue by bquorning** [rubocop-hq/rubocop-rspec#669]
I recently saw code similar to this in a spec file:

```rb
RSpec.describe Foo do
  subject { described_class.new }

  it 'does its thing' do
    some { setup }
    some.other.setup
    is_expected.to be_truthy
  end
end
```

That expectation – `is_expected.to be_truthy` – struck me as weird. I understand the readability of the one-liner version, e.g. `it { is_expected.to be_truthy }`, but when there is more than one line in the block, that expectation syntax is strange.

Would it be possible to check for – and disallow – this syntax?

**Comment by Darhazer** [comment]
Yes, that would be a good cop. I can take on it in the next couple of weeks

**Comment by Drenmi** [comment]
I agree that this makes it weird for multiline blocks, but I think `it` with additional descriptor also could disqualify the implicit version:

```ruby
it "does its thing" do
  is_expected.to be_truthy
end
```

WDYT?

**Comment by bquorning** [comment]
Good point, @Drenmi.

On a maybe-related note, I could see myself wanting to completely disable the `it { some_expectation }` syntax. Do we currently have a cop that would do this, or does RSpec have a configuration for it?

**Comment by Darhazer** [comment]
`ExampleWithoutDescription` configured with `EnforcedStyle: disallow` will complain about `it` not having a description
