### ISSUE TITLE
FactoryBot::AttributeDefinedStatically improvement

### ISSUE THREAD

**Issue by flyerhzm** [rubocop-hq/rubocop-rspec#672]
I agree that we should declare attribute values as blocks if attribute values are method calls

```
# bad
kind [:active, :rejected].sample

# good
kind { [:active, :rejected].sample }

# bad
closed_at 1.day.from_now

# good
closed_at { 1.day.from_now }
```

but I don't think it's necessary if attribute values are static, like

```
# I don't think it's bad
count 1

# I don't think it's good
count { 1 }
```

If you think it's correct, I'll send a PR.

**Comment by bquorning** [comment]
We used to have a `FactoryBot/StaticAttributeDefinedDynamically` cop that checked this exact thing. But it was removed in rubocop-rspec v1.28.0 when `FactoryBot/AttributeDefinedStatically` was added – see #666 – as a consequence of FactoryBot deprecating static attributes.
