### ISSUE TITLE
FactoryBot rules don't seem to work

### ISSUE THREAD

**Issue by mockdeep** [rubocop-hq/rubocop-rspec#674]
On version `1.28.0`. I've got the following factory, but for some reason the `FactoryBot/AttributeDefinedStatically` rule isn't reporting any issues, though `FactoryBot` itself raises an error.

```rb
# spec/factories/free_accounts.rb
FactoryBot.define do
  factory :free_account do
    email { Faker::Internet.email }
    password 'blahblah'
    password_confirmation 'blahblah'
  end
end
```

```
$ rubocop -V
0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.0 x86_64-linux)
```

**Comment by bquorning** [comment]
> … though `FactoryBot` itself raises an error.

Which error is raised by FactoryBot?

**Comment by mockdeep** [comment]
nm, turns out I'm running into [this](https://github.com/rubocop-hq/rubocop/issues/6021). RuboCop changed behavior to overwrite the `AllCops: Include`.

**Comment by alagos** [comment]
For anyone having this issue on minitest.
What I did was to copy all the factory files to `spec/factories`, run the cop and then copy all the files fixed back to the original folder.

**Comment by andrii-baran-nfgp** [comment]
@alagos Thank you. Saved my day
