### ISSUE TITLE
Some deprecated FactoryBot static attributes are not detected or auto-corrected

### ISSUE THREAD

**Issue by ragesoss** [rubocop-hq/rubocop-rspec#676]
If a model has an attribute that is a Ruby keyword, you need to use `self.attribute` to set the value in a factory. For example:

```ruby
factory :course do
    start Date.new(2015, 1, 1)
    self.end Date.new(2015, 6, 1)
end
```

Only the `start` attribute is detected as a rubocop violation and fixed.

After running rubocop-rspec (per the FactoryBot deprecation warning), it looks like this, with the second deprecated instance still there:

```ruby
factory :course do
    start { Date.new(2015, 1, 1) }
    self.end Date.new(2015, 6, 1)
end
```

**Comment by bquorning** [comment]
Thank you for reporting, @ragesoss – it looks like a fix is in progress already, at #677.
