### ISSUE TITLE
considering `::` for methods describe

### ISSUE THREAD

**Issue by Ana06** [rubocop-hq/rubocop-rspec#680]
only `#` and `.` can are considered methods inside a describe here: https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/describe_method.rb#L26

But according to [BetterSpecs](http://www.betterspecs.org/) `::` can also be used... :thinking: 

Also, why is `.` used? Ruby always uses `::` in its documentation. Maybe there should be cop to enforce this... :thinking:

**Comment by bquorning** [comment]
I have always used `.` (e.g. `Foo.bar`) to describe class methods and `#` (e.g. `Foo#bar`) to describe instance methods. But I don’t know if I can find documentation for claiming it is a “standard” :-)

**Comment by Ana06** [comment]
It seems `.` is more widely used and it would be nice to have a convention. Maybe it is enough with documented it in this cop and in [BetterSpecs](https://github.com/lelylan/betterspecs), then it will become standard :rofl:

**Comment by bquorning** [comment]
Just in https://github.com/rubocop-hq/ruby-style-guide I see something over 20 examples of using `#` between class name and instance method name (search for `Object#to_s`, `String#+`, `Hash#key?`) while `::` is only used in code examples. So my recommendation still stands, use `.` for class methods and `#` for instance methods.

**Comment by Ana06** [comment]
@bquorning 

> Just in https://github.com/rubocop-hq/ruby-style-guide I see something over 20 examples of using # between class name and instance method name (search for Object#to_s, String#+, Hash#key?) while :: is only used in code examples. So my recommendation still stands, use . for class methods and # for instance methods.

Is `#` used for class methods? :confused: 

I think it is find to encourage the use of `.`, as long as it is documented to avoid future confusions/discussions. :wink:

**Comment by pirj** [comment]
Actually, [RSpec Style Guide](https://github.com/rubocop-hq/rspec-style-guide#describe-the-methods) defines this in a pretty non-ambiguous way:

> Use the Ruby documentation convention of `.` when referring to a class method’s name and `#` when referring to an instance method’s name.

Not sure if `RSpec/DescribeMethod` covers all the cases.
However, I don't see a good reason to relax the cop and allow `::`.

WDYT?

**Comment by pirj** [comment]
There are no updates on this for quite a while. @Ana06 do you mind if we close this?
