### ISSUE TITLE
f2018091801 - Use regex for prefixes in ContextWording rules

### ISSUE THREAD

**Issue by dimitrovv** [rubocop-hq/rubocop-rspec#686]
I'd like to request a change to the [RSpec/ContextWording](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ContextWording). It would be good to have a **regex** comparison for the **ContextWording** instead of checking whether the context's description starts with a word.

We often use contexts describing instance & class methods like this:

```ruby
context '#perform' do
  ...

context '.factory' do
  ...
```

The current solution does not allow us to do this by extending the prefixes, because if splits the description and does a check whether it starts with one of the prefixes.

**Comment by dimitrovv** [comment]
I guess, `.` and `#` would be enough, but it would work with the current solution because it expects to be the first word: ex:
* `# perform` -> valid
* `#perform` -> invalid

However, we need to configure it so the `#perform` is a valid context description. I can PR this using regex, but don't think it will work with the [current implementation](https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/context_wording.rb#L45)

**Comment by dimitrovv** [comment]
The same has already been suggested in [#417 (comment)](https://github.com/rubocop-hq/rubocop-rspec/issues/417#issuecomment-342953107), so I can PR it to #417 and close this one

**Comment by bquorning** [comment]
Also related: #601

**Comment by Darhazer** [comment]
@dimitrovv #417 actually suggest the opposite - to flag `context '#perform' do` and suggest using `describe '#perform'` instead.

**Comment by bquorning** [comment]
I also noticed the keyword “describing“ in this sentence:

> We often use contexts describing instance & class methods like this:

I would recommend using `describe` for describing methods.

**Comment by dimitrovv** [comment]
OK, this should work but it 's strange. We have `describe` at the top of the described class and below we will have `describe` again for instance/class method. I don't think using `describe` in the middle of the spec is good, should be only at the top or I am wrong.

**Comment by bquorning** [comment]
Using `describe` in the middle of the spec is perfectly fine. https://relishapp.com/rspec/rspec-core/v/3-8/docs/example-groups/basic-structure-describe-it says

> The `describe` method creates an example group. Within the block passed to `describe` you can declare nested groups using the `describe` or `context` methods, or you can declare examples using the `it` or `specify` methods.

**Comment by dimitrovv** [comment]
OK I see @bquorning @Darhazer but we strictly use `describe` only once at the beginning. I'd like to PR this and add a regex possibility for the prefixes of the context description. Is it OK?

**Comment by bquorning** [comment]
Sorry, but I am 👎 on this suggestion. I would recommend using `describe` instead of `context` for describing methods.

Another option is to write a custom cop (a subclass of `RSpec/ContextWording`) that you include in your project for enforcing your preferred style.
