### ISSUE TITLE
Autocorrect skipped for FactoryBot/AttributeDefinedStatically in some cases

### ISSUE THREAD

**Issue by anthony-robin** [rubocop-hq/rubocop-rspec#687]
When an attribute is passed in the `do/end` block and used to define the value, autocorrection of the `FactoryBot/AttributeDefinedStatically` cop does not work.

Given this factory,

```ruby
factory :user do |f| 
  f.first_name 'John' # not being autocorrected
  last_name 'Doe'     # autocorrected properly
end 
```

it doesn't take into consideration the `first_name` attribute because of the `f.` before:
```ruby
# After running autocorrection

factory :user do |f| 
  f.first_name 'John'
  last_name { 'Doe' }
end 
```

Useful informations:
- Rubocop: `0.59.1 (using Parser 2.5.1.2, running on ruby 2.3.3 x86_64-darwin17)`
- Rubocop RSpec: `1.29.1`
- FactoryBot: `4.11.1`

**Comment by bquorning** [comment]
In the case
```rb
factory :user do |f| 
  f.first_name 'John' # not being autocorrected
  last_name 'Doe'     # autocorrected properly
end
```
which method is called on the `User` instance? `#first_name` or `#first_name=`?

**Comment by anthony-robin** [comment]
The method call on the `User` instance is `#first_name=`.
