### ISSUE TITLE
Pointless AggregateFailuresByDefault config option of RSpec/MultipleExpectations

### ISSUE THREAD

**Issue by ixti** [rubocop-hq/rubocop-rspec#697]
Having configuration like:

``` yaml
RSpec/MultipleExpectations:
  AggregateFailuresByDefault: true
```

Effectively disables this cop, thus option itself seems to me quiet confusing. ~This option would make sense only if there will be `MaxAggregate` count as well IMO.~

**Comment by bquorning** [comment]
I tend to agree. When configured with `AggregateFailuresByDefault: true`, the only thing this cop does is warn if you have an example defined with `aggregate_failures: false` metadata, and *still* have multiple expectations in the example. I don’t know if that edge case functionality really warrants a separate configuration option.

/cc @onk @Darhazer re. #511 and #451.

**Comment by Darhazer** [comment]
At the time I thought that the option is cool as you can workaround #451 by setting it to true in a given subfolder. On the other hand, you can disable the cop for a given folder, so it doesn't matter.

Setting `aggregate_failures: false` is valid RSpec usage and I don't see any problem in supporting it, given the fact that we already have this option. I don't see a value in the option either, as if someone sets  aggregate_failures to false, he knows what he's going. As @onk introduced the option, he can have a better perspective. Generally, we can add some documentation to the option, or we can deprecate it and later remove it.
