### ISSUE TITLE
Limit amount of llowed aggregated expectations

### ISSUE THREAD

**Issue by ixti** [rubocop-hq/rubocop-rspec#698]
Is there any interest in having `MaxAggregated` (or `AggregatedMax`) options for `MultipleExpectations` cop?

**Comment by bquorning** [comment]
There is already a `Max` config option for `MultipleExpectations`. Does that cover your use case?

**Comment by ixti** [comment]
The idea I had was something like this, consider config like this:

``` yaml
RSpec/MultipleExpectations:
  Max: 1
  MaxAggregated: 1
```

Thus following should pass:

``` ruby
it "works with single expectation" do
  expect(something).to be_ok
end

it "works with aggregated expectations" do
  aggregate_failures do
    expect(something).to be_ok
    expect(something).not_to be_bad
  end
end
```

But following to fail:

``` ruby
it "fails due to Max limit" do
  expect(something).to be_ok
  expect(something).not_to be_bad
end

it "fails due to MaxAggregated limit" do
  aggregate_failures do
    expect(something).to be_ok
    expect(something).not_to be_bad
    expect(other).to be_bad
  end
end

it "fails due to Max limit" do
  aggregate_failures do
    expect(something).to be_ok
    expect(something).not_to be_bad
  end

  expect(other).to be_bad
end
```

In other words I want to enforce Max expectations per example (naturally, I want aggregate_failures to be counted as single expectation, just like it is now). And in addition I want to limit amount of expectations in `aggregate_failures` blocks.

Not sure how good/bad is that. I'll explain rationale. I want to enforce single expectation per example, and max N expectations per aggregate_failures bock.

**Comment by bquorning** [comment]
> I'll explain rationale. I want to enforce single expectation per example, and max N expectations per aggregate_failures bock.

I don’t think I understand *why* you want to enforce max N expectations per `aggregate_failures` block.

**Comment by ixti** [comment]
I don't know how to answer this question. By the same reason why I want to enforce max N expectations per example group... o_O

Anyway, I think this answers my initial question if there's any interest in that. For my case I guess I'll just enable aggregate_filures globally and bump Max limit of this cop to 5. :D

**Comment by ixti** [comment]
In fact ended up simply disabling this cop :D
