### ISSUE TITLE
Extend metadata for RSpec cops?

### ISSUE THREAD

**Issue by bquorning** [rubocop-hq/rubocop-rspec#699]
@Darhazer  Does RuboCop-RSpec need to add the same kind of metadata that was added to RuboCop in https://github.com/rubocop-hq/rubocop/pull/6293 in order to work properly after RuboCop’s next release?

**Comment by Darhazer** [comment]
Generally - yes, this way we would be able to use the new options in Rubocop. I'll take care of this

**Comment by pirj** [comment]
@Darhazer do you mind sharing your branch? I can take this over if you like.

**Comment by pirj** [comment]
Oh, I see it https://github.com/rubocop-hq/rubocop-rspec/pull/721

**Comment by Darhazer** [comment]
Thank you @pirj for tackling this
