### ISSUE TITLE
Inconsistent behavior of SubjectStub

### ISSUE THREAD

**Issue by ixti** [rubocop-hq/rubocop-rspec#705]
``` ruby
# fails
expect(subject).to receive(:my_method)
expect(subject).to receive(:my_method).and_call_original
expect(subject).to receive(:my_method).and_wrap_original { |m, *| m.call(42) }

# passes
expect(subject).not_to receive(:my_method)
```

It should either fail on `not_to` and `to_no`; or it should pass when matcher has `and_call_original` or `and_wrap_original` modifiers.

**Comment by ur5us** [comment]
Somewhat related: with the current implementation/error message it’s not clear to me why that would be a bad thing to begin with. When I stub a method on the subject it’s exactly what I want because I don’t care about testing `#my_method` itself, only that it gets called, e.g. composing a result.

**Comment by bquorning** [comment]
The problem of stubbing the object under test is described in “Smell 1: Stubject” of https://samphippen.com/introducing-rspec-smells/, and in this Thoughtbot blog post: https://robots.thoughtbot.com/don-t-stub-the-system-under-test

But yes, the cop‘s message is very vague.
