### ISSUE TITLE
RSpec/InstanceVariable for @request/@routes

### ISSUE THREAD

**Issue by obfuscoder** [rubocop-hq/rubocop-rspec#715]
In Rails Controller specs I sometimes want to change parameters of the request (e.g. host, env) or adding specific routes. This is done by accessing @request or @routes. This rule complains about this usage. How can I circumvent this?

**Comment by bquorning** [comment]
I believe you can modify the request object just by e.g. `request.host`, `request.env` and not use `@request` (see https://github.com/rails/rails/blob/v5.1.2/actionpack/lib/action_controller/test_case.rb#L332)

The rspec-rails documentation has examples of how to define routes without using `@routes`, e.g. https://relishapp.com/rspec/rspec-rails/docs/controller-specs/anonymous-controller#draw-custom-routes-for-anonymous-controllers
