### ISSUE TITLE
Cop suggestion: (Mis-)using `let` to persist an object to the database

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop-rspec#744]
Here's an antipattern (IMHO) I often see:

```ruby
describe ".widget_count" do
  specify do
    widget
    expect(Catalog.widget_count).to eq(1)
  end

  let(:widget) do
    Widget.create!(name: 'my widget')
  end
end
```

The code is referencing `widget` to trigger the creation of a record in the database, but it's not obvious at all unless you read the definition of the `let`. The name fails to describe the intent.

I think it's much preferable to be explicit, e.g.

```ruby
  describe ".widget_count" do
    specify do
      create_widget
      expect(Catalog.widget_count).to eq(1)
    end

    def create_widget
      Widget.create!(name: "my widget")
    end
  end
end
```

Any thoughts? Is this some thing rubocop-rspec could/should detect?

**Comment by mikegee** [comment]
How do you envision this working? Maybe calls to `create`, `create!`, `save`, and `save!` in the `let` body?

**Comment by andyw8** [comment]
Perhaps by detecting places where there is there is a reference to a `let` which satisfies this criteria:

* Does not get assigned to anything
* Does not have any methods called on it.

**Comment by pirj** [comment]
The example you provided breaks ["incidental state" recommendation](https://github.com/rubocop-hq/rspec-style-guide#incidental-state) from RSpec Style Guide.

Unfortunately, I don't have a good idea of how to detect this syntax considering includable modules, included shared contexts etc where this method/`let` may be defined.

**Comment by andyw8** [comment]
Yeah, that would complicate things. I'm going to closet this for now until I think of an approach.
