### ISSUE TITLE
Extend DescribeMethod

### ISSUE THREAD

**Issue by geniou** [rubocop-hq/rubocop-rspec#753]
`DescribeMethod` is checking at the moment only for the second argument of the top-level `describe` to be a method name.

I can think for some extensions:

### limit `type`
By default its disabled, but maybe we can enable it if we limit it to top-level `describe` with `type: :model` This should be configurable, since `:helper` and maybe others should be checked as well.

```
# good
describe FooClass, type: :model do; end

describe 'my tests' do; end

# bad
describe 'my tests', type: :model do; end
```

### extend to nested `describe`
We could also check non-top-level `describe`. If the `type` of the top-level `describe` matches.

```
# good
describe FooClass, type: :model do
  describe '#foo' do; end
  describe '.foo' do; end
end

describe 'my tests' do
  describe 'foo' do; end
end

# bad
describe FooClass, type: :model do
  describe 'foo' do; end
end
```

What do you think?

**Comment by geniou** [comment]
Can also have a look into #680 as part if this.

**Comment by pirj** [comment]
I'm not sure I correctly understand this. Particularly, this bad example for nested `describe`:
```ruby
describe FooClass, type: :model do
  describe 'foo' do; end
end
```
gets me worries as I tend to use example groups to group similar examples, e.g. validations:
```ruby
RSpec.describe FooClass, type: :model do
  describe 'validations' do
    it 'validates the presence of the first name' do
      # ...
    end
    it 'validates uniqueness of kind' do
      # ...
    end
  end

  describe 'associations' do
    # ...
  end

  describe 'callbacks' do
    # ...
  end

  # etc
end
```

I don't really mind, however, I don't really understand the reasoning behind having several root example groups in a spec. I agree that they are still logically grouped by a spec file, however I can imagine that document output will be slightly off.

What I can think of as a middle ground is something like this:

```ruby
# Associations
RSpec.describe FooClass, type: :model do
  # association-related examples
  end
end

# Validations
RSpec.describe FooClass, type: :model do
  # validation-related examples
end
```
with or without a nested describe namespace.

I don't see that model/helper specs are any different from others, on the contrary, models have declarations in it that not necessarily result in methods being defined on that model, but still need some testing.

@geniou I don't see your point very clearly, do you mind to elaborate on this a bit?

**Comment by pirj** [comment]
@geniou Can you please shed more light on the idea?

**Comment by pirj** [comment]
There's no clear way how to proceed.
