### ISSUE TITLE
Improve RSpec/MultipleExpectations `aggregate_failures` detection

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rubocop-rspec#761]
There are cases when two `expect`s are actually a single expectation, specifically when testing matchers:
```ruby
  it 'fails if the method is called with an unexpected argument', :reset do
    expect(receiver).to receive(:something).with(any_of(1, 2)).twice
    expect { receiver.something(3) }
      .to fail_with('unexpected arguments')
  end
```
In this case, `MultipleExpectations` complains that there are more than two expectations, even though the first expectation is an expectation under test.

This can be reworked as a nested expectation, neither test result or cop result change:
```ruby
  it 'fails if the method is called with an unexpected argument', :reset do
    expect do
      expect(receiver).to receive(:something).with(any_of(1, 2)).twice
      receiver.something(3)
    end
      .to fail_with('unexpected arguments')
  end
```

I understand that by wrapping the whole example into an `aggregate_failures do` helps to pacify the cop, as does `:aggregate_failures` *example* metadata.

I'd agree to add `:aggregate_failures` to example *group* containing those examples. Would you accept a pull request that walks the ancestors to detects if it's set for those examples?

**Comment by Darhazer** [comment]
Sure, if setting `:aggregate_failures` to the example group changes the behavior of all examples in the group, we should respect that.

**Comment by MatheusRich** [comment]
Can we check if aggregation is enabled globally too?

```ruby
config.define_derived_metadata do
    meta[:aggregate_failures] = true
  end
```

Or should I just disable this cop entirely?

**Comment by pirj** [comment]
Disabling the cop entirely makes sense in this case @MatheusRich
