### ISSUE TITLE
Rspec/DescribedClass - No violations under user defined metadata

### ISSUE THREAD

**Issue by williams4027** [rubocop-hq/rubocop-rspec#785]
Ran into this problem recently that took me much longer than it should have to debug. But essentially I had some files that I removed some [user defined metadata](https://relishapp.com/rspec/rspec-core/docs/metadata/user-defined-metadata) from an rspec, causing new violations to surface:

Before (no violation):
```ruby
RSpec.describe Foo, :type => :request do
  it "test" do
    Foo.result
  end
end
```

After (violation):
```ruby
RSpec.describe Foo do
  it "test" do
    Foo.result # violation shows up here on Foo
  end
end
```

You can use any names here, it gives the same cop results. I would suspect there are just some issues parsing the class name under test, but wanted to make sure it was reported since I feel this could effect a decent number of projects that currently are not getting correct linting. Thanks!

**Comment by pirj** [comment]
Thanks for reporting.
Added a quick fix in #784.
