### ISSUE TITLE
Warning: unrecognized cop always exits with code 0

### ISSUE THREAD

**Issue by coorasse** [rubocop-hq/rubocop-rspec#786]
When a warning `Warning: unrecognized cop` is raised, rubocop exists with code 0.
Using `rubocop --fail-level=warning` or `Lint:
  Severity: warning` option has no effect.
We would expect to exit with status code 1.

**Comment by pirj** [comment]
I believe this belongs to [RuboCop itself](https://github.com/rubocop-hq/rubocop).
@bbatsov Can you please transfer it?

**Comment by bbatsov** [comment]
@pirj I didn't know you could transfer issues between repos. I can do it if someone tells me how.

**Comment by coorasse** [comment]
My bad. Wrong project. I close this one and open another one on rubocop

**Comment by pirj** [comment]
@bbatsov @koic [knows how to do that](https://github.com/rubocop-hq/rubocop-rspec/issues/747#issuecomment-471545536).
