### ISSUE TITLE
Auto-correct of offence Capybara/CurrentPathExpectation is not safe

### ISSUE THREAD

**Issue by Onumis** [rubocop-hq/rubocop-rspec#798]
After running the `rubocop -a`, this offence was autocorrected but caused tests to fail, where, imo, they should not.

Diff made by --autocorrect:

```
- expect(page.current_path).to eq checkout_path(checkout_id)
+ expect(page).to have_current_path checkout_path(checkout_id)
```

RSpec fails with:

```
expected "/checkouts/1fd28388-0a1e-403a-915b-ac6d5aa7e07d?access_token=51e8564762150170aa81994eca6c9792" to equal "/checkouts/1fd28388-0a1e-403a-915b-ac6d5aa7e07d"
```

Seems like `have_current_path` is using some method that includes the querystring on the path, while `page.current_path` does not.

**Comment by Onumis** [comment]
Autocorrect introduced in https://github.com/rubocop-hq/rubocop-rspec/pull/641

**Comment by bquorning** [comment]
So, `page.current_path` returns the path without querystring, but `have_current_path(...)` checks against the path including querystring.

It should be fixable by the `only_path` option:
```rb
expect(page).to have_current_path checkout_path(checkout_id, only_path: true)
```

@ypresto What’s your take on this bug report? Should we include `only_path: true` options when auto-correcting?

**Comment by Onumis** [comment]
@bquorning not sure that is the solution. Looking at how `url_for` works: https://api.rubyonrails.org/v4.2.11.1/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for

The `only_path` option seems to mean that the domain is not included (`_url` vs `_path` generators), but both querystring and anchor remain.

**Comment by Onumis** [comment]
Ah, seems like this is the approach needed: https://github.com/teamcapybara/capybara/issues/1875#issuecomment-362466731

```
expect(page).to have_current_path(checkout_path(checkout_id), ignore_query: true)

```

**Comment by bquorning** [comment]
Yeah, sorry about that – my previous comment was written too rapidly.

I did mean for `only_path: true` to be an argument to `have_current_path`, not to `checkout_path`, and of course you should use `ignore_query` instead of `only_path`. 👍
