### ISSUE TITLE
Style/VariableName doesn't enforce styles on variables defined via `let`

### ISSUE THREAD

**Issue by kjvarga** [rubocop-hq/rubocop-rspec#807]
The `Style/VariableName` rule isn't catching bad variable names (e.g. camelCase when snake_case is configured) for `let` variable definitions.

It's common in specs to define the variable using `let` and then it gets passed to methods as an argument.  Because of this bug in Rubocop, method arguments were not being enforced by `Style/VariableName` rule either: https://github.com/rubocop-hq/rubocop/issues/7275

Tested with Rubocop 0.74.0 and rubocop-rspec 1.35.0

## Expected behavior

When configured to use `snake_case`, the `Style/VariableName` rule should catch usage such as:
```
let(:badVariable) { true }
```

## Actual behavior

No Rubocop violations are found.

```
$ rubocop test.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## Steps to reproduce the problem

File: test.rb
```
# frozen_string_literal: true

let(:badVariable) { true }

def print_name(user_name)
  puts user_name
end

print_name(badVariable)
```
`rubocop test.rb` (probably need RSpec for `let`)

## RuboCop version

```
$ rubocop -V
0.74.0 (using Parser 2.6.3.0, running on ruby 2.3.7 universal.x86_64-darwin18)
```

**Comment by pirj** [comment]
Thanks for reporting this.

Sounds like an idea for a new cop, not sure if it would be possible to plug into an existing cop, and if it's a good idea at all.

Also, support for camel case as an enforced style seems weird to me.
