### ISSUE TITLE
Detect empty hooks (before, after, …)

### ISSUE THREAD

**Issue by buehmann** [rubocop-hq/rubocop-rspec#811]
This morning I found an empty `before` hook in our codebase:
```ruby
# frozen_string_literal: true

RSpec.describe Foo do
  before do
  end

  describe '#foo' do
    it { works }
  end
end
```

I would be nice if there were a cop that detected hooks with empty blocks.

**Comment by pirj** [comment]
This might be even more generic, an empty example group or an empty `let`/`let!`.
Can't tell off the top of my head if an empty example with a block means that it's pending, or just one without a block.

**Comment by buehmann** [comment]
There are the following loosely related cops:
* `RSpec/EmptyExampleGroup`: Checks if an example group does not include any tests.
* `RSpec/AroundBlock`: Checks that around blocks actually run the test.

**Comment by dgollahon** [comment]
> empty `let`/`let!`.

IIRC, this is valid / another way to write `let(:foo) { nil }`. That could be a different cop (enforce explicit nil in lets?).

Either way, empty setup methods are probably worth checking.
