### ISSUE TITLE
Add strongest rules for parse shared_context vs context

### ISSUE THREAD

**Issue by tit** [rubocop-hq/rubocop-rspec#833]
`shared_context` is not `context`, but rubocop-rspec say: `Start context description with 'when', 'with', or 'without'` on `shared_context`.

```bash
$ rubocop --require rubocop-rspec /spec/shared_context/time.rb
Inspecting 1 file
C

Offenses:

/spec/shared_context/time.rb:3:22: C: RSpec/ContextWording: Start context description with 'when', 'with', or 'without'.
RSpec.shared_context 'time' do
                     ^^^^^^

1 file inspected, 1 offense detected
```

**Comment by pirj** [comment]
Thanks for reporting this @tit.
Can you please share at least a part of `spec/shared_context/time.rb`?

**Comment by pirj** [comment]
@tit ping

**Comment by pirj** [comment]
@tit ping

**Comment by pirj** [comment]
What I originally meant is a potential misuse of `shared_context`, it's often used as `shared_examples`, and doesn't carry any context in it. On the other hand, if a shared context brings some context, chances are high that it can be named as `ContextWording` suggests, e.g. `with additional time stubs` and used correspondingly:
```ruby
include_context 'with additional time stubs'
```

Please don't get me wrong, I don't assume you write specs in a wrong way, just want to make sure we're on the same page.

In case you don't feel that this style of naming shared contexts applies to your project, it's possible to turn it off locally by placing an additional `.rubocop.yml` file in `spec/shared_context`, and disabling it locally for files under that directory:
```yml
# spec/shared_context/
RSpec/ContextWording:
  Enabled: false
```

Please let us know if there's something actionable in the scope of this issue.

**Comment by pirj** [comment]
@bquorning There's not much input from issue creator, WDYT of closing it for now?
