### ISSUE TITLE
Allow to catch RSpec/ExpectInHook offenses in the setup block

### ISSUE THREAD

**Issue by roman-dubrovsky** [rubocop-hq/rubocop-rspec#835]
`RSpec/ExpectInHook` is a great cop that allows us to detected expectation usage in the hook. Unfortunately, it does not work with `setup` block which is a part of `rspec-rails` gem. 

Here is a valid Rspec example that won't be detected via RuboCop. 

```ruby
setup do
  expect(something).to eq 'foo'
end
```

Probably, for fixing that issue we just need to extend the language dictionary and add new hook. https://github.com/rubocop-hq/rubocop-rspec/blob/0036374b8bd3cea61d9a61a911cbaeaf3541883e/lib/rubocop/rspec/language.rb#L85-L97

P.S. Probably, also we can add a new cop which can detect `setup` usage and suggest to use `before` block.

**Comment by pirj** [comment]
Related to https://github.com/rubocop-hq/rubocop-rspec/issues/333
In addition to aliases to examples/example groups, consider also configuring hooks and matchers that we treat as "built-in".

**Comment by pirj** [comment]
Would you like to take a stab on this @roman-dubrovsky ?
It encompasses renaming `ALL` in `Language::Hooks` to `BUILTIN`, adding a `CUSTOM` that would load custom hooks from `AllCops/RSpec`, and adding an `ALL` as a union of `BUILTIN` and `CUSTOM`. Plus, documentation on how to configure it in the project using RuboCop RSpec.

That would be a solid first step to solve a number of outstanding issues related to RSpec DSL extensions that RuboCop RSpec previously did not consider.

**Comment by lazycoder9** [comment]
@roman-dubrovsky let me try to handle this. I will work on it @pirj

**Comment by pirj** [comment]
@roman-dubrovsky I'm closing this, since RSpec Rails doesn't seem to recommend using `setup`, but rather use more conventional `before`, `after` and `around` hooks. `setup` comes from Minitest, and RSpec Rails [wraps it into hooks](https://github.com/rspec/rspec-rails/blob/13a8a01cc07c93db97b5f1cd57229527441cd626/lib/rspec/rails/adapters.rb#L106).

In any case, this will be handled in #1077
