### ISSUE TITLE
Regression 1.36.0: RSpec/Pending ignores skip/pending with a string

### ISSUE THREAD

**Issue by bbugh** [rubocop-hq/rubocop-rspec#840]
We have some legacy specs that use `skip: "message"` along with a `rubocop:disable RSpec/Pending` for business reasons.

The line of code in question is correctly skipped by RSpec, but Rubocop v1.36.0 no longer correctly reports that it is a pending. 

```ruby
# Correctly reports error in 1.35.0 but is ignored in 1.36.0 
feature "something", skip: "Running tests this way is unreliable" do

# Correctly reports error in both v1.35.0 and v1.36.0
feature "something", skip: true do
```

✅ Rubocop 1.35.0

```
Inspecting 1 file
C

Offenses:

spec/feature/feature_spec.rb:5:1: C: RSpec/Pending: Pending spec found.
feature "something", skip: "Running tests this way is unreliable" do
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

❌ Rubocop 1.36.0

```
Inspecting 1 file
.

1 file inspected, no offenses detected
```

It looks like it changed in the commit here by @pirj: https://github.com/rubocop-hq/rubocop-rspec/commit/ae86c40273ec6158cddde6f549836b262a28a95c#diff-04b4d0a706cb7a2e1af0c5d7e00fbbcf

I don't really understand what that code is doing, but my best guess based on the previous code is that it's no longer testing for truthy values.

**Comment by pirj** [comment]
Thanks for bringing this up @bbugh 👍

**Comment by bbugh** [comment]
Rad, thanks for the quick fix!
