### ISSUE TITLE
Stubbing `__send__`

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rubocop-rspec#842]
I've noticed the following in one project:
```ruby
expect(something).to receive(:__send__).with(action_name, argument)
```

It results in a warning message coming from rspec-mocks:
```
lib/rspec/mocks/method_double.rb:265: warning: removing `__send__' may cause serious problems
```

Can't come up with a good reason to stub `__send__`/`send`/`public_send` when a `with` qualifier is given with a defined method name. Although it might be hard to distinguish a local var/method call from argument matchers like `anything`/`any_args`.

Also affects `have_received`/`receive_method_chain`/`receive_messages`.

With spies it might be slightly more complicated as it might involve generic expectation without `with`:
```ruby
allow(something).to receive(:__send__)
...
expect(something).to have_received(:__send__).with(action_name, argument)
```
making auto-correction of `allow` call impossible.

I could tackle this. @bquorning @Darhazer @dgollahon what are your thoughts on this?

**Comment by pirj** [comment]
Ping

**Comment by bquorning** [comment]
I think the warning from rspec-mocks is fine. Do you feel that rubocop-rspec should also warn users of the same problem?

**Comment by pirj** [comment]
In general, rspec-mocks' warning is enough to give an idea that something is wrong. On the other hand, some people tend to ignore warnings, while RuboCop checks are often part of CI's checks and in some way affect or are automatically added to pull requests as code review notes that makes them more visible.

Another concern is that that warning is a bit cryptic, as it mentions removal "removing `__send__'", not stubbing itself, and it adds an additional step to understand that it removes something that was stubbed.

I believe we had a conversation already that what's covered by RSpec's warnings should be added as a "Non-goals of RuboCop RSpec", and I agree with that.

The only benefit of this cop would be the auto-correction option, but with the complexity of supporting it for spies, I'm not convinced this will be bug-free.

Also, this is such a rare case, that I'm more inclined to close this for now.
