### ISSUE TITLE
Cop idea: detect repeated describe/context description

### ISSUE THREAD

**Issue by lazycoder9** [rubocop-hq/rubocop-rspec#856]
In the company, we had a situation when someone pushed specs with duplicated context occasionally and only PR reviewers caught it.
```ruby
context "when cool thing happens" do
    # some examples
end

context "when cool thing happens" do
    # some examples
end
```

We tried to find some cops in `rubocop-rspec` which will detect this kind of occasion, but there were only `RSpec/RepeatedExample` and `RSpec/RepeatedDescription` and these cops do not detect repeated descriptions in `describe/context`, only examples.
So my question is, does it worth to implement different cops for `describe/context` like above ones or we can extend them to cover these cases?

**Comment by pirj** [comment]
It does make sense to add a new cop. Should be pretty straightforward, since `RepeatedDescription` is very similar code-wise.

**Comment by lazycoder9** [comment]
@pirj Hey, thanks for reply. Actually, several days ago I've already created [PR](https://github.com/datarockets/datarockets-style/pull/149) I'm our company's rubocop repository with new 4 cops. And yes, I took main ideas from `RSpec/RepeatedDescription` implementation, but code is still very raw - there is not enough test cases in cops' specs. So, if you agree, I can move this PR here and firstly create PR only with `describe` nodes and enhance implementation. What do you think?

**Comment by pirj** [comment]
Perfect!
I'm thinking that `RepeatedDescribeBody` and `RepeatedContextDescription` could be merged into one with a couple changes:
```diff
- (begin (block (send nil? :context ...) ...)+ )
+ (begin (block (send nil? {:context :describe} ...) ...)+ )
```
There are actually more example group types (`example_group`/`feature`/...) all conveniently pre-defined [here](https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/rspec/language.rb#L48) so it's possible to use:
```ruby
def_node_matcher :example_group?, ExampleGroups::ALL.block_pattern
```
```
(begin (block (send nil? #example_group? ...) ...)+ )
```
Also, group them by example group type:
```diff
- .group_by { |child| [extract_metadata(child), extract_body(child)] }
+ .group_by { |child| [child.method_name, extract_metadata(child), extract_body(child)] }
```
