### ISSUE TITLE
Is `rubocop-rspec` require `require: false` in gemfile entry

### ISSUE THREAD

**Issue by ShockwaveNN** [rubocop-hq/rubocop-rspec#857]
RuboCop Readme has entry, that RuboCop should be added in gemfile with `require: false` param
https://github.com/rubocop-hq/rubocop/blame/master/README.md#L47

Does `rubocop-rspec` should be default with same param? Or it inherit this value from `rubocop`?

**Comment by Darhazer** [comment]
This has nothing to do with `rubocop` or `rubocop-rspec`, but with the fact, that this is a tool usually used in development, and run command line, so you don't need your app to actually load Rubocop or it's extensions.

So I would say
```rb
gem 'rubocop-rspec', require: false
```
would be the preferred way to add `rubocop-rspec` to your Gemfile.

**Comment by ShockwaveNN** [comment]
@Darhazer Ok, thanks. Should I create PR with addition to README?

**Comment by pirj** [comment]
Yes, please @ShockwaveNN
