### ISSUE TITLE
RSpec/EmptyExampleGroup passes when invalid examples nodes are found

### ISSUE THREAD

**Issue by mlarraz** [rubocop-hq/rubocop-rspec#864]
Consider the following example:
```ruby
RSpec.describe "addition" do
  before do
    it "does something" do
      expect(1 + 1).to eq(2)
    end
  end
end
```

`#it` is not available inside this context, so we would expect an exception to raise. However, since there are no examples, the `before` block is never executed.

The `RSpec/EmptyExampleGroup` rule should catch this, but because there is technically an `it` inside the `describe` block, it passes. The end result is both RSpec and Rubocop pass, but the test and setup are never executed.

**Comment by pirj** [comment]
Good catch.
I've seen `before` inside a `before` and was always wondering how it has passed so many spec runs.

**Comment by pirj** [comment]
Pull request is welcome.
I suggest changing `def_node_search` to `def_node_matcher` and the following:
```diff
- return unless example_group?(node) && !contains_example?(node)
+ return unless example_group?(node)
+ return if node.children.any?(:&contains_example?)
```
