### ISSUE TITLE
Unexpected Style/MethodCallWithArgsParentheses warning for chained expectations

### ISSUE THREAD

**Issue by nomasprime** [rubocop-hq/rubocop-rspec#870]
I'm getting `Style/MethodCallWithArgsParentheses` warning but surely that cop should ignore this kind of example:

```
expect { entity.destroy(params) }
  .to change { Tag.all.count }.by(-1)
  .and change { Tagging.all.count }.by(-1)
```

**Comment by pirj** [comment]
Even though the code is a spec, the cop is from main `rubocop`. I suggest you to open an issue there and add the offence message and your related configuration for the cop for completeness.

**Comment by nomasprime** [comment]
I realised that but added here because I thought Rubocop RSpec would override Rubocop, that's not the case?

**Comment by pirj** [comment]
No, at least I'm not aware if this is possible somehow.

One thing I may suggest is to put RSpec-specific RuboCop rules in `spec` directory.

However, the examples that you mention in this issue and also the other seem to make sense in general for different DSLs, not only for RSpec. Let's see what RuboCop core guys say.
