### ISSUE TITLE
Unexpected Lint/AmbiguousBlockAssociation warning

### ISSUE THREAD

**Issue by nomasprime** [rubocop-hq/rubocop-rspec#871]
Get a warning for:

```
expect { entity.destroy(params) }
  .not_to change { Media.all.count }
```

But not for:

```
expect { entity.destroy(params) }
  .to change { Tag.count }.from(1).to(0)
```

**Comment by pirj** [comment]
Even though the code is a spec, the cop is from [main `rubocop`](https://github.com/rubocop-hq/rubocop-rspec/issues/). I suggest you open an issue there and add the offence message and your related configuration for the cop for completeness.
