### ISSUE TITLE
RSpec/RepeatedDescription take metadata into account

### ISSUE THREAD

**Issue by lazycoder9** [rubocop-hq/rubocop-rspec#873]
According to this [comment](https://github.com/rubocop-hq/rubocop-rspec/pull/860#discussion_r367659300) from @pirj, there is an issue with `RSpec/RepeatedDescription` cop. This issue does not take metadata of examples into account and registers offense for examples like
```ruby
it 'do something' do
  # ...
end

it 'do something', :flag do
  # ...
end
```

And examples above should not be flagged

**Comment by pirj** [comment]
Nice catch! Would you be interested in submitting a pull request?

**Comment by lazycoder9** [comment]
@pirj sure, why not
