### ISSUE TITLE
Bug in RSpec/RepeatedDescription

### ISSUE THREAD

**Issue by bquorning** [rubocop-hq/rubocop-rspec#876]
In v1.38.0 (after #874), RSpec/RepeatedDescription started reporting “Don't repeat descriptions within an example group” on descriptions consisting of interpolated strings.

Example of a failing spec:
```rb
  it 'does not flag similar descriptions with different interpolated variables' do
    expect_no_offenses(<<-RUBY)
      describe 'doing x' do
        it "does #{x}" do
        end

        it "does #{y}" do
        end
      end
    RUBY
  end
```

As far as I can tell, there are two problems involved:

1. `RuboCop::RSpec::Example#doc_string` only considering `str` and not `dstr` nodes in https://github.com/rubocop-hq/rubocop-rspec/blob/v1.38.0/lib/rubocop/rspec/example.rb#L7
2. `signatures.any?` return true for `[[], nil]` in  https://github.com/rubocop-hq/rubocop-rspec/blob/v1.38.0/lib/rubocop/cop/rspec/repeated_description.rb#L64

**Comment by pirj** [comment]
@lazycoder9 Looks similar to how you've covered it in [`RepeatedExampleGroupDescription`](https://github.com/rubocop-hq/rubocop-rspec/pull/860/files#diff-496c3e81c602aa626d84fe6ca8a3e8e6R179). Do you have time to take a look?

**Comment by lazycoder9** [comment]
@pirj yeah, pretty similar, will look into it ASAP

**Comment by jimbali** [comment]
Getting this issue too since the last update. Example:
```
%i[foo bar].each do |type|
  it "does a thing #{type}" do
    ...
  end
end
```
```
C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.
  it "does a thing #{type}" do
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pirj** [comment]
Wondering if it's a separate case or the same problem.
Are there any other similar example description in the same example group, or just this one inside the interation @jimbali ?

**Comment by jimbali** [comment]
It's actually more like:
```
%i[foo bar].each do |type|
  it "does a thing #{type}" do
    ...
  end
end

%i[foz baz].each do |type|
  it "does a thing #{type}" do
    ...
  end
end
```

**Comment by bquorning** [comment]
I think it’s the `str` vs `dstr` issue I mentioned. I have a failing case like this:
```rb
describe "foo" do
  it "bar #{x}" do
    expect(x).to eq(2)
  end

  it "baz #{y}" do
    expect(y).to eq(3)
  end
end
```
```
C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.
    it "bar #{x}" do
    ^^^^^^^^^^^^^
C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.
    it "baz #{y}" do
    ^^^^^^^^^^^^^
```

**Comment by pirj** [comment]
Let's make sure the ones inside iterators are distinguished properly, even if docstrings are identical.

**Comment by lazycoder9** [comment]
@pirj @bquorning locally, I've fixed issue with `dstr` and cases like 
```ruby
describe "foo" do
  it "bar #{x}" do
    expect(x).to eq(2)
  end

  it "baz #{y}" do
    expect(y).to eq(3)
  end
end
```
does not registers offenses. But I wonder how examples inside iterators can be solved (or even should be solved)? But it is OK for a case like this
```ruby
describe 'doing x' do
  %i[foo bar].each do |type|
    it "does a thing \#{type}" do
    end
  end
end

describe 'doing x' do
  %i[foz baz].each do |type|
    it "does a thing \#{type}" do
    end
  end
end
```
WDYT?

**Comment by bquorning** [comment]
I see what you mean. In your code example the example group descriptions (`"doing x"`) are identical, and the code _could_ be written as
```rb
describe 'doing x' do
  %i[foo bar foz baz].each do |type|
    it "does a thing \#{type}" do
    end
  end
end
```

I would imagine that would be very hard to detect (and even harder to autocorrect).

But identical examples or example descriptions within the same iterator can be detected, right? E.g.
```rb
describe 'doing x' do
  %i[foo bar].each do |type|
    it "does a thing \#{type}" do
    end

    it "does a thing \#{type}" do
    end
  end
end
```

**Comment by lazycoder9** [comment]
@bquorning Yeap, I've added test case with the last examples in same iterator and offenses were detected

**Comment by jimbali** [comment]
Also broken since the last release:
```
it 'has a long description has a long description' \
   'that continues on the next line' do
  ...
end

it 'has a completely different long description' \
   'with something else on the next line' do
  ...
end
```
```
C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.
        it 'has a long description has a long description ' \ ...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
C: RSpec/RepeatedDescription: Don't repeat descriptions within an example group.
       it 'has a completely different long description' \ ...
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pirj** [comment]
This should be pretty much covered with `dstr`:
```
$ ruby-parse -e "'a' \             
dquote> 'b'"
(dstr
  (str "a")
  (str "b"))
```
Won't hurt to add an example though.

**Comment by lazycoder9** [comment]
@jimbali nice case to test, will check it too
