### ISSUE TITLE
RSpec/EmptyExampleGroup raises when using only shared examples in a context

### ISSUE THREAD

**Issue by jsugarman** [rubocop-hq/rubocop-rspec#884]
**using rubocop-rspec (1.38.1)**
this cop raises a violation for a block in which there are only shared_example calls

**Example using cancancan ability_spec**
```
RSpec.configure do |config|
  config.alias_it_behaves_like_to :is_able_to, 'is able to'
end

RSpec.shared_examples 'perform search' do
  it { is_expected.to be_able_to(%i[new create], SearchFilter) }
  it { is_expected.to be_able_to(%i[new create], Search) }
end


RSpec.describe Ability, type: :model do
  subject(:ability) { described_class.new(user) }

  # cop violated on this block
  # rubocop:disable RSpec/EmptyExampleGroup
  context 'when a manager' do
    let(:user) { create(:user, roles: ['manager']) }
    is_able_to 'perform search'
  end
  # rubocop:enable RSpec/EmptyExampleGroup
end
```

**Comment by pirj** [comment]
I suspect this is not because there are shared examples only, but because of an alias that `rubocop-rspec` is unaware of.
Related: #333

**Comment by pirj** [comment]
Handled in #1077

Appreciate if you could tackle a pull request to CanCanCan, @jsugarman

**Comment by pirj** [comment]
@jsugarman Example PRs https://github.com/palkan/action_policy/pull/138, https://github.com/test-prof/test-prof/pull/199
