### ISSUE TITLE
Allow to specify a prefix for RSpec/FilePath

### ISSUE THREAD

**Issue by AlexWayfer** [rubocop-hq/rubocop-rspec#895]
Hello.

I have [Flame web-framework](https://github.com/AlexWayfer/flame) (Ruby gem) with `unit/` and `integration/` specs for it.

Unit are just for classes, as usual. But integration for mocking HTTP requests.

I'm getting offenses from `RSpec/FilePath` about any unit spec because of `unit/` directory.

It'd be great to specify something like:

```yaml
RSpec/FilePath:
  Prefix: 'unit/'
```

But I'm not sure about offenses from `integration/`.

Yes, as work-around I can move all unit-specs to the root `spec/` directory, but it'd be not so obvious to find `integration/` specs.

Semi-related to #429

**Comment by pirj** [comment]
That's strange.
Can you debug [this](https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/file_path.rb#L58) and see why it doesn't match the glob?
```ruby
return if filename_ends_with?(glob)
```

**Comment by AlexWayfer** [comment]
Oh, I'm sorry, it's my inattentive.

I had to add `flame/` to file names. 

So, renaming `unit/` to `flame/` resolves these offenses and is OK for me.
