### ISSUE TITLE
Reason and rationale behind certain cops (RSpec/MultipleExpectations and RSpec/ExampleLength)

### ISSUE THREAD

**Issue by OmriSama** [rubocop-hq/rubocop-rspec#916]
Hi everyone

At work we have several Rails gems and applications that have had tests build many years ago. I would love to use `rubocop-rspec` to refactor and clean some of them, but unfortunately as I've noticed with many cops from various gems, there is usually not enough reasoning or rationale behind the cops or the specific default values chosen.

Specifically, `MultipleExpectations` and `ExampleLength` seem very restrictive to me. I 100% agree that many of my tests should be made shorter, but do most RSpec suites actually use one `expect` per test? And are most examples 5 lines or shorter? How were these numbers picked or decided?

What if you want to do 'workflow' based tests where you have examples that depend on a complex set of steps that need to have some continuity?

Thanks!

**Comment by pirj** [comment]
@OmriSama 


We could possibly say just like RuboCop itself does "Out of the box it will enforce many of the guidelines outlined in the community Ruby Style Guide", but in regards to https://rspec.rubystyle.guide/. However, unfortunately, this wouldn't be completely true.

The default configuration options grew naturally, some of the things were "enforced", and became a mainstream way amongst those who just drop in `rubocop-rspec` to their projects.

RuboCop RSpec is configurable, and users are really encouraged to configure it to meet their style. I've seen quite some completely different styles being used, and RuboCop RSpec helping out with enforcing them.

I don't seem anything horrible in the default config, that would break safe and good practices, really.

We're conservative about changing the defaults. However, those defaults are not set in stone, and given enough argumentation we'll be happy to make the change. (an example when the argumentation played against the request https://github.com/rubocop-hq/rubocop-rspec/issues/868).

Keep in mind that changing the defaults will affect all of the existing users of RuboCop RSpec, and according to https://docs.rubocop.org/en/latest/versioning/ should only happen in the major releases. RuboCop itself still didn't hit 1.0 just yet, and for us, there's just not enough of things that would make up a good 2.0 release with some freshly changed defaults.

Even though I've pushed for the removal of the strict `one example one expectation` from the style guide, it doesn't mean one expectation per example is a bad thing from the stylistic point of view. It originally meant "one **business** expectation", not "one literal expectation".

As for testing a complex set of steps, it depends on what you mean exactly.
> RSpec is a DSL for creating executable examples of how code is expected to
behave

Would agree that testing your complex set of steps would fit into:
```
before do
  step_1
  step_2
  ...
  step 237
end

it 'reaches the top' do
  expect(climber).to be_at_the_top_of_the_staircase
end
```

I would disagree with probing intermittent results after each step, even though probably in some rare cases it's the best option. For those an inline `rubocop:disable RSpec/ExampleLength, RSpec/MultipleExpectations` will do the job.

Please feel free to open a ticket if you feel that something specific in the defaults needs to be addressed.
