### ISSUE TITLE
Update cops documentation rake task

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop-rspec#922]
I've noticed in this commit https://github.com/rubocop-hq/rubocop-rspec/commit/c673d8962e5c453d12a64e71319b001b29b4b7ea that still the legacy docs are being updated. Guess I forgot about the rake task that generates them and we'll need to update it as we did for the other gems.

**Comment by bbatsov** [comment]
That's basically the necessary change - https://github.com/rubocop-hq/rubocop-minitest/pull/81

**Comment by pirj** [comment]
I guess our doc generation is in order now. Is this correct, @bquorning?
