### ISSUE TITLE
RSpec/EmptyLineAfterSubject triggers on factories

### ISSUE THREAD

**Issue by itay-grudev** [rubocop-hq/rubocop-rspec#923]
I have the following FactoryBot factory:

```ruby
factory :announcement do
  subject { 'Subject' }
  message { 'Message' }
end
```

And of course I get:
```
Add empty line after `subject`
```

I think the rule can be applied by default only to files matching the following name pattern: `spec/**/*_spec.rb` which of course would exclude `spec/factories.rb`.

That is also the default `rspec` filename filter AFAIK.

**Comment by pirj** [comment]
Nice catch. I think there was a similar problem in the past, or there's still an open ticket.
Would you like to tackle this?

I imagine you'd have to tweak this logic https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/cop.rb#L43 or maybe take a look at the other RuboCop extensions how they manage to do this.
Last time I've checked, https://github.com/rubocop-hq/rubocop-minitest didn't have anything related.

Another simpler option would be to tweak the pattern here https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml#L6

**Comment by pirj** [comment]
For the reference https://github.com/rubocop-hq/rubocop-rspec/issues/703
