### ISSUE TITLE
RSpec/PredicateMatcher breaks Ranges.

### ISSUE THREAD

**Issue by schwern** [rubocop-hq/rubocop-rspec#926]
RSpec's `include` and `include?` are not equivalent. Here is a demonstration with `Range`.

The original test.

```
require 'rspec'

describe 'include' do
  it 'is not equivalent' do
    range = (Time.now...Time.now)
    expect(range.include?(Time.now)).to be_falsey
  end
end
```

It passes.

```
$ rspec test_spec.rb 
.

Finished in 0.00274 seconds (files took 0.07717 seconds to load)
1 example, 0 failures
```

Run rubocop autocorrect RSpec/PredicateMatcher.

```
$ rubocop -a test_spec.rb --only RSpec/PredicateMatcher
Inspecting 1 file
C

Offenses:

test_spec.rb:6:5: C: [Corrected] RSpec/PredicateMatcher: Prefer using include matcher over include?.
    expect(range.include?(Time.now)).to be_falsey
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

The test is "corrected".

```
require 'rspec'

describe 'include' do
  it 'is not equivalent' do
    range = (Time.now...Time.now)
    expect(range).not_to include(Time.now)
  end
end
```

And now fails.

```
$ rspec test_spec.rb 
F

Failures:

  1) include is not equivalent
     Failure/Error: expect(range).not_to include(Time.now)
     
     TypeError:
       can't iterate from Time
     # ./test_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.00313 seconds (files took 0.07706 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./test_spec.rb:4 # include is not equivalent
```

**Comment by pirj** [comment]
Are you certain that the problem is not with `Time.now` being evaluated at different times?

```ruby
RSpec.describe 'include' do
  it 'is not equivalent' do
    range = (3..5)
    expect(range.include?(6)).to be_falsey
  end

  it 'is not equivalent' do
    range = (3..5)
    expect(range).not_to include(6)
  end
end
```

both are green.

**Comment by pirj** [comment]
Please disregard my previous assumption, however the example still stands.

It seems to be a bug in `rspec-expectations` related to Time ranges. Appreciate if you file a ticket [there](https://github.com/rspec/rspec-expectations/issues/new).

`RSpec/PredicateMatcher` has been [tagged as unsafe for autocorrect](https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml#L448), so it is how it is.

I assume RSpec should work fine with time ranges, and if it doesn't, it would be strange to skip the offence by default if it still works just fine with numeric ranges or ranges of strings (`('a'..'n')`).

**Comment by pirj** [comment]
@schwern you mention "and similar problems". What problems exactly, what matchers/predicates?

**Comment by schwern** [comment]
@pirj rspec-expectations appears to be replacing `range.include?` with `range.each`. For example, `Integer` works, but `Floats` have the same problem.

```
require 'rspec'

describe 'include' do
  it 'is not equivalent' do
    obj = 2.5
    range = (obj...obj)
    expect(range.include?(obj)).to be_falsey  # pass
    expect(range).not_to include(obj)  # TypeError: can't iterate from Float
  end
end
```

**Comment by schwern** [comment]
@pirj And thanks for reporting it upstream.

**Comment by pirj** [comment]
> Float has the same problem

👍 

Thanks for reporting, and you're always welcome!
