### ISSUE TITLE
RSpec/VariableName: Would appreciate an 'ignore' configuration option

### ISSUE THREAD

**Issue by jtannas** [rubocop-hq/rubocop-rspec#941]
**Feature Request**
A configuration option to specify certain variables or patterns to ignore

**Example**
```yaml
RSpec/VariableName:
  Enabled: true
  EnforcedStyle: "snake_case"
  IgnoreVariables:
    - fooBar
    - /fizzBuzz/
```
**Context**
We use an RSpec plugin called [RSwag](https://github.com/rswag/rswag) that allows the creation of specs & swagger documentation from a single DSL. One of the features is that documented parameters can be populated in tests via `let` statements

eg.
```ruby
describe 'Blogs API - Individual Blog Endpoint' do
  path '/blogs/{id}' do
	parameter(name: :id, in: :path, required: true, type: :string)
    let(:id) { 'foo' }
	# test code ensues
  end
end
```

The issue arises when providing an array as a query parameter
```ruby
describe 'Blogs API - Blog Collection Endpoint' do
  path '/blogs' do
    # making a request to /blogs?id[]=foo&id[]=bar&id[]=baz
    parameter(
      name: :'id[]',
      in: :query,
      required: false,
      type: :array,
      items: { type: :string },
      collectionFormat: :multi,
    )
    let(:'id[]') { ['foo', 'bar', 'baz'] } # sets off the cop
    # test code ensues
  end
end 
```

It's way too much of a corner case to modify the cop to ignore that specific pattern, but I think a generic option to ignore certain things by name or regex is appropriate.

**Comment by pirj** [comment]
That's quite a strange name for a variable defined with `let`, but I guess it fits RSwag's style.
With an empty default `Ignore:` setting it is welcome, so is a pull request.
