### ISSUE TITLE
Remove `RSpec/EmptyExampleGroup`'s `CustomIncludeMethods` config option

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rubocop-rspec#969]
It may be replaced with a global or cop-local configuration for RSpec aliases when #956 is implemented.

Bonus points:
 - [x] find other such configuration options and fix in a similar way

**Comment by bquorning** [comment]
> * [ ]  find other such configuration options and fix in a similar way

We should probably do this work before 2.0.

**Comment by pirj** [comment]
@bquorning This is done actually. I [couldn't find any cop-specific RSpec DSL configuration](https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml) apart from `EmptyExampleGroup`.

**Comment by bquorning** [comment]
I guess we can check the box and close this issue then?

**Comment by pirj** [comment]
It will be automatically resolved when #1007 is merged to `master`.
We'll have to go through our open tickets after releasing anyway, since e.g. there are numerous tickets resolved by #956, e.g. #333, which are not referenced by #956 as `fixes #...`.

**Comment by pirj** [comment]
I wasn't automatically resolved for some reason. Let us quickly help you, Github.
