### ISSUE TITLE
`RSpec/ExampleLength` breaks with rubocop master

### ISSUE THREAD

**Issue by tejasbubane** [rubocop-hq/rubocop-rspec#974]
**StackTrace:**

```
An error occurred while RSpec/ExampleLength cop was inspecting /Users/tejas.bubane/opensource/rubocop-ast/spec/rubocop/ast/node_spec.rb:203:8.
undefined method `irrelevant_line' for #<RuboCop::Cop::RSpec::ExampleLength:0x00007fc20d4fdf18>
Did you mean?  relevant_file?
/Users/tejas.bubane/.rvm/gems/ruby-2.7.1/gems/rubocop-rspec-1.39.0/lib/rubocop/cop/rspec/example_length.rb:46:in `block in code_length'
/Users/tejas.bubane/.rvm/gems/ruby-2.7.1/gems/rubocop-rspec-1.39.0/lib/rubocop/cop/rspec/example_length.rb:46:in `count'
/Users/tejas.bubane/.rvm/gems/ruby-2.7.1/gems/rubocop-rspec-1.39.0/lib/rubocop/cop/rspec/example_length.rb:46:in `code_length'
/Users/tejas.bubane/.rvm/gems/ruby-2.7.1/gems/rubocop-rspec-1.39.0/lib/rubocop/cop/rspec/example_length.rb:36:in `on_block'
```

Example failing build: https://github.com/rubocop-hq/rubocop-ast/pull/30/checks?check_run_id=884738237

**Reason:**

`RSpec/ExampleLength` uses [#irrelevant_line](https://github.com/rubocop-hq/rubocop-rspec/blob/0cad53a9ba5a96161be78a315262d9a8da959782/lib/rubocop/cop/rspec/example_length.rb#L46) which was removed in the refactor https://github.com/rubocop-hq/rubocop/pull/8356. Rubocop continues to use it from [here](https://github.com/rubocop-hq/rubocop/blob/994fe7c754189675ec32d2b111f02b5232a062f3/lib/rubocop/cop/metrics/utils/code_length_calculator.rb#L147-L150).

We should probably configure CI to run specs with rubocop-master as well.

**Comment by pirj** [comment]
> We should probably configure CI to run specs with rubocop-master as well.

We have that check.

![image](https://user-images.githubusercontent.com/6916/87852386-3092bb80-c90a-11ea-9ec1-2980a1c7f97d.png)

RuboCop should probably add checks so that major known extensions don't break due to refactorings ;)

A pull request is much appreciated. I personally lack knowledge about the refactoring in question.
Please feel free to bump the minimum required `rubocop` version to avoid supporting two different APIs.

**Comment by marcandre** [comment]
> > We should probably configure CI to run specs with rubocop-master as well.
> 
> We have that check.

I'm confused; https://github.com/rubocop-hq/rubocop/pull/8356 was all green, even though it was breaking `rubocop-rspec` and the `internal_investigation` runs rubocop-rspec... How is that possible?

**Comment by tejasbubane** [comment]
> I'm confused; rubocop-hq/rubocop#8356 was all green, even though it was breaking rubocop-rspec and the internal_investigation runs rubocop-rspec... How is that possible?

@marcandre This might be because rubocop uses bundled [rubocop-rspec](https://github.com/rubocop-hq/rubocop/blob/master/Gemfile#L13) (which in-turn uses bundled rubocop) instead of a master version.

**Comment by pirj** [comment]
> How is that possible?

Good question!

According to git blame, the line containing `irrelevant_line` [didn't undergo any changes for three years now](https://github.com/rubocop-hq/rubocop-rspec/blame/master/lib/rubocop/cop/rspec/example_length.rb#L46).

**Comment by pirj** [comment]
@tejasbubane You seem to be right since the bundled `~> 1.39.0` probably didn't use edge `rubocop` with the changes in the pull request, but rather RuboCop's latest released version from RubyGems.

**Comment by marcandre** [comment]
> @tejasbubane You seem to be right since the bundled `~> 1.39.0` probably didn't use edge `rubocop` with the changes in the pull request, but rather RuboCop's latest released version from RubyGems.

It kind of has to be right, but that's suprising; the `internal_investigation` is a rake task that should be using the current repo for the `rubocop` gem...

**Comment by marcandre** [comment]
I put that method back for the time being...

**Comment by pirj** [comment]
Please correct me if I'm wrong, I see the following problems here:
 - rubocop-rspec is not in line with a recent refactoring, a cop should be fixed to address this
 - RuboCop core's internal investigation is not using its own branch
 - RuboCop's API changes may break its known extensions, there are no measures against that

I can take care of the first issue if you like and file tickets for the rest. Sounds good?

**Comment by marcandre** [comment]
For the third point, I want to make it clearer what is public API and what isn't. The mixins (like in this case) will have public methods and (at least from v1+) we should really worry about compatibility...

**Comment by pirj** [comment]
I guess there's nothing actionable left.

As a preventive measure, do you think it makes sense to add a `gem :rubocop, '< 1.0'` to our gemspec, @marcandre ?
RuboCop RSpec 2.0 will be fully compatible with all the RuboCop 1.0 API changes, and will depend on `rubocop` `'>= 1.0'`.

**Comment by marcandre** [comment]
> As a preventive measure, do you think it makes sense to add a gem :rubocop, '< 1.0' to our gemspec, @marcandre ?

I don't think it's not needed (especially since we're already publishing breaking changes in the 0.x branch).
