### ISSUE TITLE
RSpec/SharedContext: needs CustomIncludeMethods setting

### ISSUE THREAD

**Issue by zverok** [rubocop-hq/rubocop-rspec#975]
This setting exists for `RSpec/EmptyExampleGroup`, and is needed for `SharedContext` too: otherwise, the cop creates false positives with custom methods akin to `its(:foo) { ... }`. 
We use [those](https://github.com/zverok/saharspec#its-addons), but I believe there are several gems providing additional methods.

**Comment by pirj** [comment]
Agree, the detection of `its` etc needs to be supported, probably not limited to `EmptyExampleGroup` and `SharedContext`, but some existing, future and custom cops.

Adding aliases and configuring acceptable DSL is currently in the works in #956, it should pretty much cover this case.

Keeping this ticket open to remember about this case (we have quite a number of tickets that this DSL configuration will resolve).

Related: #333

**Comment by pirj** [comment]
PS we plan to drop `CustomIncludeMethods` in #969, and release it with 2.0 when the DSL configuration from #956 will be able to substitute what `CustomIncludeMethods` does now.

**Comment by pirj** [comment]
#956 has been released as part 2.0.

A reference implementation on how to allow third-party gems to configure their RSpec DSL configuration for RuboCop RSpec is tracked in #1077

Appreciate if you could handle it in `saharspec` provided the preliminary plan, @zverok.

**Comment by pirj** [comment]
@zverok Example PRs https://github.com/palkan/action_policy/pull/138, https://github.com/test-prof/test-prof/pull/199
