### ISSUE TITLE
Cop to detect and rewrite top level `describe` -> `RSpec.describe`?

### ISSUE THREAD

**Issue by ioquatix** [rubocop-hq/rubocop-rspec#985]
Since `disable_monkey_patching!` will be a requirement in RSpec 4, should we make a cop to support this change in legacy specs?

**Comment by pirj** [comment]
Sorry, it's a non-goal for RuboCop RSpec https://docs.rubocop.org/rubocop-rspec/index.html#enforcing-an-explicit-rspec-receiver-for-top-level-methods-disabling-monkey-patching

I believe RSpec should provide necessary tooling to assist with the migration to RSpec 4, like it was with RSpec 3 and transspec.

**Comment by ioquatix** [comment]
Okay, fair enough :)
