### ISSUE TITLE
Cop Idea: Detect repeated include_examples in same context

### ISSUE THREAD

**Issue by biinari** [rubocop-hq/rubocop-rspec#992]
Similar to #260, we should detect identical includes of [shared examples](https://relishapp.com/rspec/rspec-core/v/3-9/docs/example-groups/shared-examples) within an example group.

This should be a violation (spotted in [spec for rubocop Style/ConditionalAssignment](https://github.com/rubocop-hq/rubocop/blob/1fc19811eef1f70a103cddee4b34e4e8a863b8c7/spec/rubocop/cop/style/conditional_assignment_assign_to_condition_spec.rb#L724-L725)):

```ruby
RSpec.describe RuboCop::Cop::Style::ConditionalAssignment do
  it_behaves_like('all assignment types', '=')
  it_behaves_like('all assignment types', '+=')
  it_behaves_like('all assignment types', '-=')

  it_behaves_like('all assignment types', '=') # violation: repeated
  it_should_behave_like('all assignment types', '+=') # violation: repeated with different syntax

  include_examples('all assignment types', '-=') # violation: similar but in current context instead of nested context
end
```

`it_behaves_like` and `it_should_behave_like` are identical (both include the examples in a nested context) so should be treated the same.

Although `include_examples` includes the examples in the current context instead of a nested context, I can't think of any cases where one would want to use different forms for the same `shared_examples`.

---

The following should not be violations:

```ruby
context 'with foo' do
  it_behaves_like 'some examples', 'test'

  it_behaves_like 'some examples', 'other' # ok: different parameters
  it_behaves_like 'other examples', 'test' # ok: different shared_examples
end

context 'with bar' do
  it_behaves_like 'some examples', 'test' # ok: in a different context
end
```

**Comment by pirj** [comment]
Nice!
Would you like to hack on it?

**Comment by biinari** [comment]
@pirj yeah, I fancy having a go at it.
